// Code generated by tono. DO NOT EDIT.

use crate::payments::common::types::*;

macro_rules! open_enum {
    ($name:ident : $wire:ty { $($variant:ident => $repr:expr),* $(,)? }) => {
        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                match self {
                    $($name::$variant => serde::Serialize::serialize(&$repr, s),)*
                    $name::Unknown(v) => serde::Serialize::serialize(v, s),
                }
            }
        }
        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let v = <$wire as serde::Deserialize>::deserialize(d)?;
                $(if v == $repr {
                    return Ok($name::$variant);
                })*
                Ok($name::Unknown(v))
            }
        }
    };
}

open_enum!(Status: String {
    Active => "active",
    Settled => "settled",
    Refunded => "refunded",
});
