// Code generated by tono. DO NOT EDIT.

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct LocalDate(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

#[derive(Clone, Debug)]
pub enum Status {
    Active,
    Settled,
    Refunded,
    Unknown(String),
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Card {
    pub last4: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BankAccount {
    pub iban: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind")]
pub enum PaymentMethod {
    #[serde(rename = "card")]
    Card(Card),
    #[serde(rename = "bank")]
    Bank(BankAccount),
}
