// Code generated by tono. DO NOT EDIT.

package common

import (
	"encoding/json"
	"fmt"
)

func marshalVariant(payload any, disc, tag string) ([]byte, error) {
	b, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(b, &obj); err != nil {
		return nil, err
	}
	obj[disc], _ = json.Marshal(tag)
	return json.Marshal(obj)
}

func (m PaymentMethodCard) MarshalJSON() ([]byte, error) {
	return marshalVariant(m.Value, "kind", "card")
}

func (m PaymentMethodBank) MarshalJSON() ([]byte, error) {
	return marshalVariant(m.Value, "kind", "bank")
}

func UnmarshalPaymentMethod(b []byte) (PaymentMethod, error) {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return nil, err
	}
	var tag string
	json.Unmarshal(d["kind"], &tag)
	switch tag {
	case "card":
		var p Card
		if err := json.Unmarshal(b, &p); err != nil {
			return nil, err
		}
		return PaymentMethodCard{Value: p}, nil
	case "bank":
		var p BankAccount
		if err := json.Unmarshal(b, &p); err != nil {
			return nil, err
		}
		return PaymentMethodBank{Value: p}, nil
	}
	return nil, fmt.Errorf("unknown variant %q", tag)
}
