// Code generated by tono. DO NOT EDIT.

package common

type Timestamp string

type LocalDate string

type Duration string

type Status string

const (
	StatusActive   Status = "active"
	StatusSettled  Status = "settled"
	StatusRefunded Status = "refunded"
)

type Card struct {
	Last4 string `json:"last4"`
}

type BankAccount struct {
	Iban string `json:"iban"`
}

type PaymentMethod interface{ isPaymentMethod() }

type PaymentMethodCard struct{ Value Card }

func (PaymentMethodCard) isPaymentMethod() {}

type PaymentMethodBank struct{ Value BankAccount }

func (PaymentMethodBank) isPaymentMethod() {}
