// Code generated by tono. DO NOT EDIT.

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  const n = BigInt(s);
  if (n < -9223372036854775808n || n > 9223372036854775807n) {
    throw new RangeError(`i64 out of range: ${s}`);
  }
  return n;
}

export function decodeU64(s: string): bigint {
  const n = BigInt(s);
  if (n < 0n || n > 18446744073709551615n) {
    throw new RangeError(`u64 out of range: ${s}`);
  }
  return n;
}

export function encodeBytes(b: Uint8Array): string {
  return btoa(String.fromCharCode(...b));
}

export function decodeBytes(s: string): Uint8Array {
  // Line breaks are not data. atob is lenient about a missing pad,
  // so the length and padding are checked here: a malformed value is
  // an error rather than bytes nobody sent.
  const t = s.replace(/[\r\n]/g, "");
  if (t.length % 4 !== 0 || !/^[A-Za-z0-9+/]*={0,2}$/.test(t)) {
    throw new Error(`invalid base64: ${JSON.stringify(s)}`);
  }
  return Uint8Array.from(atob(t), (c) => c.charCodeAt(0));
}
