// Code generated by tono. DO NOT EDIT.

import { BankAccount, Card, PaymentMethod, Status } from "./types";

export function encodeStatus(value: Status): string {
  return value;
}

export function decodeStatus(raw: string): Status {
  return raw as Status;
}

export function encodeCard(value: Card): unknown {
  return {
    last4: value.last4,
  };
}

export function decodeCard(raw: any): Card {
  return {
    last4: raw.last4,
  };
}

export function encodeBankAccount(value: BankAccount): unknown {
  return {
    iban: value.iban,
  };
}

export function decodeBankAccount(raw: any): BankAccount {
  return {
    iban: raw.iban,
  };
}

export function encodePaymentMethod(value: PaymentMethod): unknown {
  switch (value.kind) {
    case "card":
      return { kind: "card", ...(encodeCard(value as any) as object) };
    case "bank":
      return { kind: "bank", ...(encodeBankAccount(value as any) as object) };
  }
  throw new Error("unknown variant");
}

export function decodePaymentMethod(raw: any): PaymentMethod {
  switch (raw.kind) {
    case "card":
      return { kind: "card", ...(decodeCard(raw) as object) } as PaymentMethod;
    case "bank":
      return {
        kind: "bank",
        ...(decodeBankAccount(raw) as object),
      } as PaymentMethod;
  }
  throw new Error("unknown variant");
}
