// Code generated by tono. DO NOT EDIT.

export type Status = "active" | "settled" | "refunded" | (string & {});

export interface Card {
  last4: string;
}

export interface BankAccount {
  iban: string;
}

export type PaymentMethod =
  ({ kind: "card" } & Card) | ({ kind: "bank" } & BankAccount);
