// Code generated by tono. DO NOT EDIT.

use crate::duration::parse_duration_ms;
use crate::env::read_env;
use crate::http::{
    backoff_delay_ms, check_transport, default_random, default_sleep, has_header, http_send,
    http_send_with_timeout, resolve_max_retries, set_header, RandomFn, SleepFn,
};
use crate::support::{ClientOptions, Duration, HttpRequest, HttpTransport};

use crate::payments::charges::types::*;

/// Settings are the resolved construction values of the client entry.
/// Exactly one transport slot may be set: `client` (native `reqwest`,
/// present only with the crate's default-on `reqwest` feature) or
/// `transport` (canonical). `headers` are the base request headers; a
/// declared `@header` wins only where nothing else set the name.
pub(crate) struct Settings {
    pub api_key: String,
    pub endpoint: String,
    pub timeout: Duration,
    pub max_retries: i32,
    #[cfg(feature = "reqwest")]
    pub client: Option<reqwest::Client>,
    pub transport: Option<HttpTransport>,
    pub headers: std::collections::HashMap<String, String>,
}

/// The payments SDK entry: the construction surface and its operations.
pub struct Client {
    #[allow(dead_code)]
    settings: Settings,
    #[allow(dead_code)]
    options: ClientOptions,
    timeout_ms: f64,
    pub(crate) sleep: SleepFn,
    pub(crate) random: RandomFn,
}

/// Resolves the endpoint construction value.
fn resolve_setting_endpoint() -> String {
    if let Some(v) = read_env("PAYMENTS_ENDPOINT") {
        let parsed: String;
        parsed = v;
        return parsed;
    }
    "https://api.payments.example.com".to_string()
}

/// Resolves the timeout construction value.
fn resolve_setting_timeout(with: Option<Duration>) -> Duration {
    if let Some(v) = with {
        return v;
    }
    Duration("10s".to_string())
}

/// Resolves the max_retries construction value.
fn resolve_setting_max_retries(with: Option<i32>) -> i32 {
    if let Some(v) = with {
        return v;
    }
    2
}

pub struct ClientBuilder {
    api_key: String,
    timeout: Option<Duration>,
    max_retries: Option<i32>,
}

impl ClientBuilder {
    pub fn with_timeout(mut self, v: Duration) -> Self {
        self.timeout = Some(v);
        self
    }
    pub fn with_max_retries(mut self, v: i32) -> Self {
        self.max_retries = Some(v);
        self
    }

    /// Resolves the declared sources top-down, then the declared
    /// validation.
    pub fn build(self) -> Result<Client, TonoError> {
        self.build_with_transport(None)
    }

    /// `build` plus the transport seam the generated tests construct through:
    /// a `Some` transport replaces whatever construction resolved, so a
    /// test answers canonically without a server.
    pub(crate) fn build_with_transport(
        self,
        transport: Option<HttpTransport>,
    ) -> Result<Client, TonoError> {
        let mut s = Settings {
            api_key: String::new(),
            endpoint: String::new(),
            timeout: Duration(String::new()),
            max_retries: 0,
            #[cfg(feature = "reqwest")]
            client: None,
            transport: None,
            headers: std::collections::HashMap::new(),
        };
        s.api_key = self.api_key;
        s.endpoint = resolve_setting_endpoint();
        s.timeout = resolve_setting_timeout(self.timeout.clone());
        s.max_retries = resolve_setting_max_retries(self.max_retries);
        let mut violations: Vec<Violation> = Vec::new();
        if s.api_key.chars().count() < 1 {
            violations.push(Violation {
                field: "api_key".to_string(),
                constraint: "length".to_string(),
                message: "api_key length must be >= 1".to_string(),
            });
        }
        if !violations.is_empty() {
            return Err(TonoError::Validation(ValidationError { violations }));
        }
        let timeout_ms = match parse_duration_ms(&s.timeout.0) {
            Ok(ms) => ms,
            Err(_) => {
                return Err(TonoError::Config(ConfigError {
                    message: format!("timeout: invalid duration {:?}", s.timeout.0),
                }));
            }
        };
        if let Some(t) = transport {
            s.transport = Some(t);
            #[cfg(feature = "reqwest")]
            {
                s.client = None;
            }
        }
        let options = ClientOptions {
            #[cfg(feature = "reqwest")]
            client: s.client.clone(),
            transport: s.transport.clone(),
            headers: s.headers.clone(),
        };
        if let Err(message) = check_transport(&options) {
            return Err(TonoError::Config(ConfigError { message }));
        }
        Ok(Client {
            settings: s,
            options,
            timeout_ms,
            sleep: default_sleep(),
            random: default_random(),
        })
    }
}

impl Client {
    /// The entry point of the builder: the @arg values positionally,
    /// @with values configured through `.with_*` before `.build()`.
    pub fn builder(api_key: String) -> ClientBuilder {
        ClientBuilder {
            api_key,
            timeout: None,
            max_retries: None,
        }
    }
    pub async fn create_charge(&self, input: Charge) -> Result<Charge, TonoError> {
        if let Err(e) = input.validate() {
            return Err(TonoError::Validation(e));
        }
        let url = format!("{}{}", self.settings.endpoint, "/charges".to_string());
        let mut headers: std::collections::HashMap<String, String> =
            std::collections::HashMap::new();
        set_header(&mut headers, "X-API-Key", self.settings.api_key.clone());
        for (k, v) in &self.options.headers {
            set_header(&mut headers, k, v.clone());
        }
        let body = Some(serde_json::to_string(&input).map_err(|e| {
            TonoError::Config(ConfigError {
                message: format!("input serialization: {e}"),
            })
        })?);
        if !has_header(&headers, "content-type") {
            headers.insert("content-type".to_string(), "application/json".to_string());
        }
        let max_retries = resolve_max_retries(self.settings.max_retries as i64);
        let mut attempt: u32 = 0;
        loop {
            let request = HttpRequest {
                method: "POST".to_string(),
                url: url.clone(),
                headers: headers.clone(),
                body: body.clone(),
            };
            let outcome =
                match http_send_with_timeout(&self.options, request, self.timeout_ms).await {
                    Ok(response) => response,
                    Err(cause) => {
                        if attempt < max_retries {
                            (self.sleep)(backoff_delay_ms(attempt, (self.random)())).await;
                            attempt += 1;
                            continue;
                        }
                        return Err(TonoError::Transport(TransportError { cause }));
                    }
                };
            if outcome.status == 201 {
                return decode_charge(&outcome.body);
            }
            let err = decode_create_charge_error(outcome.status, &outcome.body);
            if attempt < max_retries && err.retryable() {
                (self.sleep)(backoff_delay_ms(attempt, (self.random)())).await;
                attempt += 1;
                continue;
            }
            return Err(err);
        }
    }
    pub async fn latest_charge(&self) -> Result<Option<Charge>, TonoError> {
        let url = format!(
            "{}{}",
            self.settings.endpoint,
            "/charges/latest".to_string()
        );
        let mut headers: std::collections::HashMap<String, String> =
            std::collections::HashMap::new();
        set_header(&mut headers, "X-API-Key", self.settings.api_key.clone());
        for (k, v) in &self.options.headers {
            set_header(&mut headers, k, v.clone());
        }
        let request = HttpRequest {
            method: "GET".to_string(),
            url: url.clone(),
            headers: headers.clone(),
            body: None,
        };
        let outcome = match http_send(&self.options, request).await {
            Ok(response) => response,
            Err(cause) => return Err(TonoError::Transport(TransportError { cause })),
        };
        if outcome.status >= 200 && outcome.status < 300 {
            return {
                let body = &outcome.body;
                let trimmed = body.trim();
                if trimmed.is_empty() || trimmed == "null" {
                    Ok(None)
                } else {
                    let decoded = decode_charge(body);
                    decoded.map(Some)
                }
            };
        }
        Err(TonoError::Api(APIFailure::Undeclared(APIError {
            status: outcome.status,
            body: outcome.body,
        })))
    }
}

pub fn decode_create_charge_error(status: u16, body: &str) -> TonoError {
    // A body that fails to decode falls straight to the fallback, which
    // carries the raw body as APIError.
    let value: serde_json::Value = match serde_json::from_str(body) {
        Ok(value) => value,
        Err(_) => {
            return TonoError::Api(APIFailure::Undeclared(APIError {
                status,
                body: body.to_string(),
            }))
        }
    };
    if status == 402 && value.pointer("/code").and_then(|v| v.as_str()) == Some("card_declined") {
        if let Ok(data) = serde_json::from_value::<CardDeclined>(value.clone()) {
            return TonoError::Api(APIFailure::CardDeclined(data));
        }
    }
    if status == 404 {
        if let Ok(data) = serde_json::from_value::<NotFound>(value.clone()) {
            return TonoError::Api(APIFailure::NotFound(data));
        }
    }
    TonoError::Api(APIFailure::Undeclared(APIError {
        status,
        body: body.to_string(),
    }))
}
