// Code generated by tono. DO NOT EDIT.

pub fn parse_duration_ms(v: &str) -> Result<f64, ()> {
    let mut rest = v;
    let mut sign = 1.0;
    if let Some(r) = rest.strip_prefix('-') {
        sign = -1.0;
        rest = r;
    } else if let Some(r) = rest.strip_prefix('+') {
        rest = r;
    }
    if rest == "0" {
        return Ok(0.0);
    }
    let units: [(&str, f64); 8] = [
        ("ns", 1e-6),
        ("\u{b5}s", 1e-3),
        ("\u{3bc}s", 1e-3),
        ("us", 1e-3),
        ("ms", 1.0),
        ("s", 1000.0),
        ("m", 60000.0),
        ("h", 3_600_000.0),
    ];
    let mut total = 0.0;
    let mut consumed = 0usize;
    let bytes = rest.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        let start = i;
        while i < bytes.len() && bytes[i].is_ascii_digit() {
            i += 1;
        }
        let mut has_digits = i > start;
        if i < bytes.len() && bytes[i] == b'.' {
            i += 1;
            let frac_start = i;
            while i < bytes.len() && bytes[i].is_ascii_digit() {
                i += 1;
            }
            has_digits = has_digits || i > frac_start;
        }
        if !has_digits {
            break;
        }
        let num: f64 = match rest[start..i].parse() {
            Ok(n) => n,
            Err(_) => break,
        };
        let unit_start = i;
        let matched = units
            .iter()
            .find(|(u, _)| rest[unit_start..].starts_with(u));
        let Some((u, mult)) = matched else {
            break;
        };
        i = unit_start + u.len();
        total += num * mult;
        consumed = i;
    }
    if consumed != rest.len() || rest.is_empty() {
        return Err(());
    }
    Ok(sign * total)
}
