// Code generated by tono. DO NOT EDIT.

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

impl std::fmt::Display for Timestamp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

impl std::fmt::Display for Duration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// The boxed, `Send` future every async transport seam returns (a
/// canonical transport's call, the retry sleep seam).
pub type BoxFuture<'a, T> = std::pin::Pin<Box<dyn std::future::Future<Output = T> + Send + 'a>>;

/// The error a transport attempt fails with; the generated client
/// classifies it into its own error taxonomy.
pub type HttpError = Box<dyn std::error::Error + Send + Sync>;

/// HttpRequest is the request the generated client builds before sending
/// it. `body` is `None` when the request carries no body.
#[derive(Clone, Debug)]
pub struct HttpRequest {
    pub method: String,
    pub url: String,
    pub headers: std::collections::HashMap<String, String>,
    pub body: Option<String>,
}

/// HttpResponse is the response the generated client reads before
/// classifying it. Header keys are lowercased (HTTP header names are
/// case-insensitive).
#[derive(Clone, Debug)]
pub struct HttpResponse {
    pub status: u16,
    pub headers: std::collections::HashMap<String, String>,
    pub body: String,
}

/// HttpTransport adapts any HTTP stack by mapping HttpRequest to
/// HttpResponse, without emulating `reqwest`. One call is one attempt:
/// the generated client owns retry, so a transport with internal
/// retries does not combine with it.
pub type HttpTransport = std::sync::Arc<
    dyn Fn(HttpRequest) -> BoxFuture<'static, Result<HttpResponse, HttpError>> + Send + Sync,
>;

/// ClientOptions is what construction froze off the resolved Settings,
/// shared across every operation. Exactly one transport slot may be
/// set: `client` (native `reqwest`, present only with the crate's
/// default-on `reqwest` feature) or `transport` (canonical); setting
/// both is a construction error, and with the feature off the
/// canonical slot is required. No slot ships its own auth; a declared
/// `@header` sets one through `headers`.
pub struct ClientOptions {
    #[cfg(feature = "reqwest")]
    pub client: Option<reqwest::Client>,
    pub transport: Option<HttpTransport>,
    pub headers: std::collections::HashMap<String, String>,
}
