// Code generated by tono. DO NOT EDIT.

package charges

import "encoding/json"
import "example.com/sdk/payments/common"

func (c *Charge) UnmarshalJSON(b []byte) error {
	type alias Charge
	var tmp struct {
		alias
		Method json.RawMessage `json:"method"`
	}
	tmp.alias = alias(*c)
	if err := json.Unmarshal(b, &tmp); err != nil {
		return err
	}
	*c = Charge(tmp.alias)
	if len(tmp.Method) > 0 {
		m, err := common.UnmarshalPaymentMethod(tmp.Method)
		if err != nil {
			return err
		}
		c.Method = m
	}
	return nil
}

func DecodeCreateChargeError(status int, body []byte) error {
	var probe struct {
		Code string `json:"code"`
	}
	_ = json.Unmarshal(body, &probe)
	if status == 402 && probe.Code == "card_declined" {
		var data CardDeclined
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	if status == 404 {
		var data NotFound
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	return &APIError{Status: status, Body: string(body)}
}
