// Code generated by tono. DO NOT EDIT.

package charges

import "context"
import tonohttp "github.com/tono-lang/tono/runtimes/http-go"
import "net/http"
import "example.com/sdk/payments/common"
import "strconv"

type Timestamp string

type LocalDate string

type Duration string

// A small payments API that exercises the hard wire cases end to end.
type Charge struct {
	ID     string `json:"id"`
	Amount int64  `json:"amount,string"`
	// Deprecated: folded into amount
	Fee      uint64               `json:"fee,string"`
	Receipt  []byte               `json:"receipt"`
	Currency string               `json:"currency"`
	Note     *string              `json:"note,omitempty"`
	Tags     []string             `json:"tags"`
	Metadata map[string]string    `json:"metadata"`
	Created  Timestamp            `json:"created"`
	Status   common.Status        `json:"status"`
	Method   common.PaymentMethod `json:"method"`
}

func ValidateCharge(value Charge) error {
	violations := []Violation{}
	if value.Amount < 0 {
		violations = append(violations, Violation{Field: "amount", Constraint: "range", Message: "amount must be >= 0"})
	}
	if len([]rune(value.Currency)) < 3 {
		violations = append(violations, Violation{Field: "currency", Constraint: "length", Message: "currency length must be >= 3"})
	}
	if len([]rune(value.Currency)) > 3 {
		violations = append(violations, Violation{Field: "currency", Constraint: "length", Message: "currency length must be <= 3"})
	}
	if len(violations) > 0 {
		return &ValidationError{Violations: violations}
	}
	return nil
}

type HTTPCode int

const (
	HTTPCodeOk       HTTPCode = 200
	HTTPCodeNotFound HTTPCode = 404
	HTTPCodeError    HTTPCode = 500
)

// A page of results with an optional continuation cursor.
type Page[T any] struct {
	Items      []T     `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// The card issuer declined the charge.
type CardDeclined struct {
	Message string `json:"message"`
}

// No charge exists for the requested id.
type NotFound struct {
	Message string `json:"message"`
}

type Violation struct {
	Field      string `json:"field"`
	Constraint string `json:"constraint"`
	Message    string `json:"message"`
}

type ValidationError struct {
	Violations []Violation `json:"violations"`
}

func (e *ValidationError) Error() string { return "validation failed" }

func (e *ValidationError) sdkError() {}

type TransportError struct {
	Cause error
}

func (e *TransportError) Error() string { return "transport failure" }

func (e *TransportError) Unwrap() error { return e.Cause }

func (e *TransportError) sdkError() {}

type DecodeError struct {
	Path     string
	Expected string
	Raw      string
}

func (e *DecodeError) Error() string { return "response body did not match the declared schema" }

func (e *DecodeError) sdkError() {}

type ContractError struct {
	ContractName string
	Cause        error
}

func (e *ContractError) Error() string { return "contract hook '" + e.ContractName + "' failed" }

func (e *ContractError) Unwrap() error { return e.Cause }

func (e *ContractError) sdkError() {}

type APIError struct {
	Status int
	Body   string
}

func (e *APIError) Error() string { return "api error " + strconv.Itoa(e.Status) }

func (e *APIError) sdkError() {}

type ConfigError struct {
	Message string
}

func (e *ConfigError) Error() string { return e.Message }

func (e *ConfigError) sdkError() {}

func (e *CardDeclined) Error() string { return "card_declined" }

func (e *CardDeclined) Retryable() bool { return true }

func (e *CardDeclined) sdkError() {}

func (e *NotFound) Error() string { return "not_found" }

func (e *NotFound) Retryable() bool { return false }

func (e *NotFound) sdkError() {}

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: HTTPClient (native) or Transport
// (canonical). Headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
type Settings struct {
	APIKey     string
	Endpoint   string
	Timeout    Duration
	MaxRetries int32

	HTTPClient *http.Client
	Transport  tonohttp.Transport
	Headers    map[string]string
}

// ClientOption configures an optional (@with) construction value of Client.
type ClientOption func(*clientOptions)

type clientOptions struct {
	timeout    *Duration
	maxRetries *int32
}

// WithTimeout sets the timeout construction value.
func WithTimeout(v Duration) ClientOption {
	return func(w *clientOptions) { w.timeout = &v }
}

// WithMaxRetries sets the max_retries construction value.
func WithMaxRetries(v int32) ClientOption {
	return func(w *clientOptions) { w.maxRetries = &v }
}

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares.
type Client struct {
	settings Settings
	runtime  *tonohttp.Runtime
	hooks    *tonohttp.Hooks
}

// ClientAPI is the operation surface of Client, for mocking.
type ClientAPI interface {
	CreateCharge(ctx context.Context, input Charge) (Charge, error)
}

var _ ClientAPI = (*Client)(nil)
