// Code generated by tono. DO NOT EDIT.

package charges

import "example.com/sdk/internal/tono"
import "context"
import "encoding/json"
import "fmt"
import tonohttp "github.com/tono-lang/tono/runtimes/http-go"
import "net/http"
import "os"

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: HTTPClient (native) or Transport
// (canonical). Headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
type Settings struct {
	APIKey     string
	Endpoint   string
	Timeout    Duration
	MaxRetries int32

	HTTPClient *http.Client
	Transport  tonohttp.Transport
	Headers    map[string]string
}

// ClientOption configures an optional (@with) construction value of Client.
type ClientOption func(*clientOptions)

type clientOptions struct {
	timeout    *Duration
	maxRetries *int32
}

// WithTimeout sets the timeout construction value.
func WithTimeout(v Duration) ClientOption {
	return func(w *clientOptions) { w.timeout = &v }
}

// WithMaxRetries sets the max_retries construction value.
func WithMaxRetries(v int32) ClientOption {
	return func(w *clientOptions) { w.maxRetries = &v }
}

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares.
type Client struct {
	settings Settings
	runtime  *tonohttp.Runtime
	hooks    *tonohttp.Hooks
}

// ClientAPI is the operation surface of Client, for mocking.
type ClientAPI interface {
	CreateCharge(ctx context.Context, input Charge) (Charge, error)
}

var _ ClientAPI = (*Client)(nil)

var createChargeDescriptor = tono.MustDescriptor("{\"bindings\":[[\"id\",{\"kind\":\"body\"}],[\"amount\",{\"kind\":\"body\"}],[\"fee\",{\"kind\":\"body\"}],[\"receipt\",{\"kind\":\"body\"}],[\"currency\",{\"kind\":\"body\"}],[\"note\",{\"kind\":\"body\"}],[\"tags\",{\"kind\":\"body\"}],[\"metadata\",{\"kind\":\"body\"}],[\"created\",{\"kind\":\"body\"}],[\"status\",{\"kind\":\"body\"}],[\"method\",{\"kind\":\"body\"}]],\"endpoint\":[\"endpoint\"],\"errors\":[[402,\"payments.charges#card_declined\",\"card_declined\",true],[404,\"payments.charges#not_found\",null]],\"http_method\":\"POST\",\"request_headers\":[[[{\"lit\":\"X-API-Key\"}],{\"field\":[\"api_key\"]}]],\"response_bindings\":[],\"retry\":{\"max\":{\"ref\":\"max_retries\"}},\"success\":[[200,{\"args\":[],\"ref\":\"payments.charges#charge\"}]],\"timeout\":{\"ref\":\"timeout\"},\"uri\":\"/charges\"}")

// New constructs Client: positional @arg values, options for @with,
// declared sources resolved top-down, client_init on top (bespoke wins),
// then the declared validation.
func New(apiKey string, opts ...ClientOption) (*Client, error) {
	w := clientOptions{}
	for _, opt := range opts {
		opt(&w)
	}
	s := Settings{Headers: map[string]string{}}
	s.APIKey = apiKey
	if v, ok := os.LookupEnv("PAYMENTS_ENDPOINT"); ok && v != "" {
		s.Endpoint = v
	} else {
		s.Endpoint = "https://api.payments.example.com"
	}
	if w.timeout != nil {
		s.Timeout = *w.timeout
	} else {
		s.Timeout = Duration("10s")
	}
	if w.maxRetries != nil {
		s.MaxRetries = *w.maxRetries
	} else {
		s.MaxRetries = int32(2)
	}
	violations := []Violation{}
	if len([]rune(s.APIKey)) < 1 {
		violations = append(violations, Violation{Field: "api_key", Constraint: "length", Message: "api_key length must be >= 1"})
	}
	if len(violations) > 0 {
		return nil, &ValidationError{Violations: violations}
	}
	values := map[string]any{}
	values["api_key"] = s.APIKey
	values["endpoint"] = s.Endpoint
	{
		ms, err := durationMs(string(s.Timeout))
		if err != nil {
			return nil, &ConfigError{Message: fmt.Sprintf("timeout: invalid duration %q", string(s.Timeout))}
		}
		values["timeout"] = ms
	}
	values["max_retries"] = int64(s.MaxRetries)
	runtime, err := tonohttp.New(tonohttp.Options{Client: s.HTTPClient, Transport: s.Transport, Headers: s.Headers, Values: values})
	if err != nil {
		return nil, err
	}
	return &Client{settings: s, runtime: runtime, hooks: nil}, nil
}

func (c *Client) CreateCharge(ctx context.Context, input Charge) (Charge, error) {
	var zero Charge
	if invalid := ValidateCharge(input); invalid != nil {
		return zero, invalid
	}
	record, err := tono.EncodeRecord(input)
	if err != nil {
		return zero, err
	}
	outcome, err := c.runtime.Execute(ctx, createChargeDescriptor, record, c.hooks)
	if err != nil {
		return zero, err
	}
	switch outcome.Kind {
	case tonohttp.OutcomeTransport:
		return zero, &TransportError{Cause: outcome.Cause}
	case tonohttp.OutcomeError:
		return zero, DecodeCreateChargeError(outcome.Status, []byte(outcome.Body))
	}
	var probe map[string]json.RawMessage
	if err := json.Unmarshal([]byte(outcome.Body), &probe); err != nil {
		return zero, &DecodeError{Path: "$", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["id"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.id", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["amount"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.amount", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["fee"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.fee", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["receipt"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.receipt", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["currency"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.currency", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["tags"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.tags", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["metadata"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.metadata", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["created"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.created", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["status"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.status", Expected: "Charge", Raw: outcome.Body}
	}
	if rv, ok := probe["method"]; !ok || string(rv) == "null" {
		return zero, &DecodeError{Path: "$.method", Expected: "Charge", Raw: outcome.Body}
	}
	var out Charge
	if err := json.Unmarshal([]byte(outcome.Body), &out); err != nil {
		return zero, &DecodeError{Path: "$", Expected: "Charge", Raw: outcome.Body}
	}
	return out, nil
}

func DecodeCreateChargeError(status int, body []byte) error {
	var probe struct {
		Code string `json:"code"`
	}
	_ = json.Unmarshal(body, &probe)
	if status == 402 && probe.Code == "card_declined" {
		var data CardDeclined
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	if status == 404 {
		var data NotFound
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	return &APIError{Status: status, Body: string(body)}
}
