// Code generated by tono. DO NOT EDIT.

package charges

import (
	"context"
	"encoding/json"
	"errors"
	"example.com/sdk/internal/transport"
	"example.com/sdk/support"
	"fmt"
	"net/http"
	"os"
	"time"
)

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: HTTPClient (native) or Transport
// (canonical). Headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
type Settings struct {
	APIKey     string
	Endpoint   string
	Timeout    support.Duration
	MaxRetries int32

	HTTPClient *http.Client
	Transport  support.HTTPTransport
	Headers    map[string]string
}

// ClientOption configures an optional (@with) construction value of Client.
type ClientOption func(*clientOptions)

type clientOptions struct {
	timeout    *support.Duration
	maxRetries *int32
}

// WithTimeout sets the timeout construction value.
func WithTimeout(v support.Duration) ClientOption {
	return func(w *clientOptions) { w.timeout = &v }
}

// WithMaxRetries sets the max_retries construction value.
func WithMaxRetries(v int32) ClientOption {
	return func(w *clientOptions) { w.maxRetries = &v }
}

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares.
type Client struct {
	settings Settings
	// timeoutDuration is the operation @timeout, converted once at construction.
	timeoutDuration time.Duration
	// timing is the clock behind the retry backoff; a test in this package
	// may pin it. The zero value uses the real clock and jitter.
	timing transport.Timing
}

// ClientAPI is the operation surface of Client, for mocking.
type ClientAPI interface {
	CreateCharge(ctx context.Context, input Charge) (Charge, error)
}

var _ ClientAPI = (*Client)(nil)

// New constructs Client: positional @arg values, options for @with,
// declared sources resolved top-down, client_init on top (bespoke wins),
// then the declared validation.
func New(apiKey string, opts ...ClientOption) (*Client, error) {
	return newWithTransport(nil, apiKey, opts...)
}

// newWithTransport is New plus the transport seam the generated tests use: a
// non-nil canonical transport replaces whatever construction resolved,
// after client_init ran, so a test answers canonically without a server.
func newWithTransport(canonical support.HTTPTransport, apiKey string, opts ...ClientOption) (*Client, error) {
	w := clientOptions{}
	for _, opt := range opts {
		opt(&w)
	}
	s := Settings{Headers: map[string]string{}}
	s.APIKey = apiKey
	if v, ok := os.LookupEnv("PAYMENTS_ENDPOINT"); ok && v != "" {
		s.Endpoint = v
	} else {
		s.Endpoint = "https://api.payments.example.com"
	}
	if w.timeout != nil {
		s.Timeout = *w.timeout
	} else {
		s.Timeout = support.Duration("10s")
	}
	if w.maxRetries != nil {
		s.MaxRetries = *w.maxRetries
	} else {
		s.MaxRetries = int32(2)
	}
	violations := []Violation{}
	if len([]rune(s.APIKey)) < 1 {
		violations = append(violations, Violation{Field: "api_key", Constraint: "length", Message: "api_key length must be >= 1"})
	}
	if len(violations) > 0 {
		return nil, &ValidationError{Violations: violations}
	}
	timeoutDuration := time.Duration(0)
	{
		d, err := time.ParseDuration(string(s.Timeout))
		if err != nil {
			return nil, &ConfigError{Message: fmt.Sprintf("timeout: invalid duration %q", string(s.Timeout))}
		}
		timeoutDuration = d
	}
	if canonical != nil {
		s.Transport = canonical
		s.HTTPClient = nil
	}
	if s.HTTPClient != nil && s.Transport != nil {
		return nil, errors.New("Settings.HTTPClient and Settings.Transport are mutually exclusive: set the native slot or the canonical slot, not both")
	}
	return &Client{settings: s, timeoutDuration: timeoutDuration}, nil
}

func (c *Client) CreateCharge(ctx context.Context, input Charge) (Charge, error) {
	var zero Charge
	if invalid := ValidateCharge(input); invalid != nil {
		return zero, invalid
	}
	requestURL := c.settings.Endpoint + "/charges"
	headers := map[string]string{}
	transport.SetHeader(headers, "X-API-Key", c.settings.APIKey)
	for name, value := range c.settings.Headers {
		transport.SetHeader(headers, name, value)
	}
	body, err := json.Marshal(input)
	if err != nil {
		return zero, err
	}
	if !transport.HasHeader(headers, "content-type") {
		headers["content-type"] = "application/json"
	}
	outcome := transport.Send(ctx, c.settings.HTTPClient, c.settings.Transport, transport.Request{
		Method:  "POST",
		URL:     requestURL,
		Headers: headers,
		Body:    body,
		Timeout: c.timeoutDuration,
		Timing:  c.timing,
		Retry: transport.Retry{Max: int(c.settings.MaxRetries), When: func(status int, body string) bool {
			if re, ok := DecodeCreateChargeError(status, []byte(body)).(interface{ Retryable() bool }); ok {
				return re.Retryable()
			}
			return false
		}},
	})
	if outcome.Cause != nil {
		return zero, &TransportError{Cause: outcome.Cause}
	}
	if outcome.Status >= 200 && outcome.Status < 300 {
		out, path, ok := DecodeCharge([]byte(outcome.Body))
		if !ok {
			return zero, &DecodeError{Path: path, Expected: "Charge", Raw: outcome.Body}
		}
		return out, nil
	}
	return zero, DecodeCreateChargeError(outcome.Status, []byte(outcome.Body))
}

func DecodeCreateChargeError(status int, body []byte) error {
	var probe struct {
		Code string `json:"code"`
	}
	// A body that fails to unmarshal leaves probe zeroed: no guard below
	// matches, and the fallback carries the raw body as APIError.
	_ = json.Unmarshal(body, &probe)
	if status == statusCardDeclined && probe.Code == codeCardDeclined {
		var data CardDeclined
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	if status == statusNotFound {
		var data NotFound
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	return &APIError{Status: status, Body: string(body)}
}
