// Code generated by tono. DO NOT EDIT.

package charges

import (
	"errors"
	"os"
	"reflect"
	"testing"
)

func TestConstructionRejectsAnEmptyApiKey(t *testing.T) {
	// Setenv records the restore; Unsetenv makes the variable truly absent.
	t.Setenv("PAYMENTS_ENDPOINT", "")
	os.Unsetenv("PAYMENTS_ENDPOINT")
	_, err := New("")
	var invalid *ValidationError
	if !errors.As(err, &invalid) {
		t.Fatalf("want a validation error, got %v", err)
	}
	violated := []string{}
	for _, v := range invalid.Violations {
		violated = append(violated, v.Field)
	}
	if want := []string{"api_key"}; !reflect.DeepEqual(violated, want) {
		t.Errorf("violated fields: got %v, want %v", violated, want)
	}
}
