// Code generated by tono. DO NOT EDIT.

package charges

import "encoding/json"
import "example.com/sdk/payments/common"
import "time"

type HTTPCode int

const (
	HTTPCodeOk       HTTPCode = 200
	HTTPCodeNotFound HTTPCode = 404
	HTTPCodeError    HTTPCode = 500
)

// A page of results with an optional continuation cursor.
type Page[T any] struct {
	Items      []T     `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// durationMs parses a duration field for the runtime's millisecond value
// positions.
func durationMs(v string) (float64, error) {
	d, err := time.ParseDuration(v)
	if err != nil {
		return 0, err
	}
	return float64(d) / float64(time.Millisecond), nil
}

func (c *Charge) UnmarshalJSON(b []byte) error {
	type alias Charge
	var tmp struct {
		alias
		Method json.RawMessage `json:"method"`
	}
	tmp.alias = alias(*c)
	if err := json.Unmarshal(b, &tmp); err != nil {
		return err
	}
	*c = Charge(tmp.alias)
	if len(tmp.Method) > 0 {
		m, err := common.UnmarshalPaymentMethod(tmp.Method)
		if err != nil {
			return err
		}
		c.Method = m
	}
	return nil
}
