// Code generated by tono. DO NOT EDIT.

package charges

import (
	"example.com/sdk/payments/common"
	"example.com/sdk/support"
	"strconv"
)

// A small payments API that exercises the hard wire cases end to end.
type Charge struct {
	ID     string `json:"id"`
	Amount int64  `json:"amount,string"`
	// Deprecated: folded into amount
	Fee      uint64               `json:"fee,string"`
	Receipt  []byte               `json:"receipt"`
	Currency string               `json:"currency"`
	Note     *string              `json:"note,omitempty"`
	Tags     []string             `json:"tags"`
	Metadata map[string]string    `json:"metadata"`
	Created  support.Timestamp    `json:"created"`
	Status   common.Status        `json:"status"`
	Method   common.PaymentMethod `json:"method"`
}

func ValidateCharge(value Charge) error {
	violations := []Violation{}
	if value.Amount < 0 {
		violations = append(violations, Violation{Field: "amount", Constraint: "range", Message: "amount must be >= 0"})
	}
	if len([]rune(value.Currency)) < 3 {
		violations = append(violations, Violation{Field: "currency", Constraint: "length", Message: "currency length must be >= 3"})
	}
	if len([]rune(value.Currency)) > 3 {
		violations = append(violations, Violation{Field: "currency", Constraint: "length", Message: "currency length must be <= 3"})
	}
	if len(violations) > 0 {
		return &ValidationError{Violations: violations}
	}
	return nil
}

// The card issuer declined the charge.
type CardDeclined struct {
	Message string `json:"message"`
}

// No charge exists for the requested id.
type NotFound struct {
	Message string `json:"message"`
}

type Violation struct {
	Field      string `json:"field"`
	Constraint string `json:"constraint"`
	Message    string `json:"message"`
}

type ValidationError struct {
	Violations []Violation `json:"violations"`
}

func (e *ValidationError) Error() string { return "validation failed" }

type TransportError struct {
	Cause error
}

func (e *TransportError) Error() string { return "transport failure" }

func (e *TransportError) Unwrap() error { return e.Cause }

type DecodeError struct {
	Path     string
	Expected string
	Raw      string
}

func (e *DecodeError) Error() string { return "response body did not match the declared schema" }

type APIError struct {
	Status int
	Body   string
}

func (e *APIError) Error() string { return "api error " + strconv.Itoa(e.Status) }

type ConfigError struct {
	Message string
}

func (e *ConfigError) Error() string { return e.Message }

func (e *CardDeclined) Error() string { return "card_declined" }

func (e *CardDeclined) Retryable() bool { return true }

func (e *NotFound) Error() string { return "not_found" }

func (e *NotFound) Retryable() bool { return false }
