// Code generated by tono. DO NOT EDIT.

const BASE64_ALPHABET =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  const n = BigInt(s);
  if (n < -9223372036854775808n || n > 9223372036854775807n) {
    throw new RangeError(`i64 out of range: ${s}`);
  }
  return n;
}

export function decodeU64(s: string): bigint {
  const n = BigInt(s);
  if (n < 0n || n > 18446744073709551615n) {
    throw new RangeError(`u64 out of range: ${s}`);
  }
  return n;
}

export function encodeBytes(b: Uint8Array): string {
  // Built from the alphabet rather than through btoa: btoa is a DOM
  // global an SDK cannot assume, and spreading the array into
  // String.fromCharCode overflows the call stack past ~128KB.
  let out = "";
  for (let i = 0; i < b.length; i += 3) {
    const n = (b[i] << 16) | ((b[i + 1] ?? 0) << 8) | (b[i + 2] ?? 0);
    out +=
      BASE64_ALPHABET[(n >> 18) & 63] +
      BASE64_ALPHABET[(n >> 12) & 63] +
      (i + 1 < b.length ? BASE64_ALPHABET[(n >> 6) & 63] : "=") +
      (i + 2 < b.length ? BASE64_ALPHABET[n & 63] : "=");
  }
  return out;
}

export function decodeBytes(s: string): Uint8Array {
  // Line breaks are not data. Every other length and padding rule is
  // checked before a byte is produced, so a malformed value is an
  // error rather than bytes nobody sent.
  const t = s.replace(/[\r\n]/g, "");
  if (t.length % 4 !== 0 || !/^[A-Za-z0-9+/]*={0,2}$/.test(t)) {
    throw new Error(`invalid base64: ${JSON.stringify(s)}`);
  }
  const body = t.replace(/=+$/, "");
  const out = new Uint8Array((body.length * 3) >> 2);
  let at = 0;
  for (let i = 0; i < body.length; i += 4) {
    let n = 0;
    const run = Math.min(4, body.length - i);
    for (let k = 0; k < run; k++) {
      n |= BASE64_ALPHABET.indexOf(body[i + k]) << (18 - 6 * k);
    }
    out[at++] = (n >> 16) & 255;
    if (run > 2) out[at++] = (n >> 8) & 255;
    if (run > 3) out[at++] = n & 255;
  }
  return out;
}
