// Code generated by tono. DO NOT EDIT.

// readEnv treats an unset and an empty variable the same: empty means
// not set, per the declared-source contract.
export function readEnv(name: string): string | undefined {
  const env = (
    globalThis as { process?: { env?: Record<string, string | undefined> } }
  ).process?.env;
  const v = env?.[name];
  return v === undefined || v === "" ? undefined : v;
}
