// Code generated by tono. DO NOT EDIT.

import { ClientOptions, HttpRequest, HttpResponse } from "./support";

// formatScalar renders a value the way the wire expects it in a path,
// query, or header position: strings verbatim, everything else as JSON.
export function formatScalar(value: unknown): string {
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value) ?? "";
  } catch {
    return "";
  }
}

// setHeader overrides across casings: header names are case-insensitive,
// so a bespoke "authorization" replaces a declared "Authorization" rather
// than riding beside it.
export function setHeader(
  headers: Record<string, string>,
  name: string,
  value: string,
): void {
  const lower = name.toLowerCase();
  for (const key of Object.keys(headers)) {
    if (key.toLowerCase() === lower) delete headers[key];
  }
  headers[name] = value;
}

export function hasHeader(
  headers: Record<string, string>,
  name: string,
): boolean {
  const lower = name.toLowerCase();
  return Object.keys(headers).some((key) => key.toLowerCase() === lower);
}

// headerRecord collects a Headers object into a plain record so a hook can
// read and rewrite it without a live Headers instance.
export function headerRecord(headers: Headers): Record<string, string> {
  const record: Record<string, string> = {};
  headers.forEach((value, key) => {
    record[key] = value;
  });
  return record;
}

// assertExclusiveTransport rejects setting both transport slots: the
// caller must pick the native slot (fetch) or the canonical one
// (transport), not both.
export function assertExclusiveTransport(options: ClientOptions): void {
  if (options.fetch && options.transport) {
    throw new Error(
      "ClientOptions.fetch and ClientOptions.transport are mutually exclusive: set the native slot or the canonical slot, not both",
    );
  }
}

// httpSend performs one attempt: the canonical transport when set,
// otherwise fetch.
export async function httpSend(
  options: ClientOptions,
  request: HttpRequest,
  signal: AbortSignal | undefined,
): Promise<HttpResponse> {
  if (options.transport) return options.transport(request, signal);
  const transport = options.fetch ?? fetch;
  const response = await transport(request.url, {
    method: request.method,
    headers: request.headers,
    body: request.body,
    signal,
  });
  const text = await response.text();
  return {
    status: response.status,
    headers: headerRecord(response.headers),
    body: text,
  };
}

// httpSendWithTimeout bounds one attempt: the timeout aborts the signal
// (so a cooperating transport cancels its work) and rejects the attempt
// regardless, so a transport that ignores the signal still times out.
export async function httpSendWithTimeout(
  options: ClientOptions,
  request: HttpRequest,
  timeoutMs: number,
): Promise<HttpResponse> {
  if (timeoutMs <= 0) return httpSend(options, request, undefined);
  const controller = new AbortController();
  let timer: ReturnType<typeof setTimeout> | undefined;
  const expiry = new Promise<never>((_, reject) => {
    timer = setTimeout(() => {
      const cause = new Error(`attempt timed out after ${timeoutMs}ms`);
      controller.abort(cause);
      reject(cause);
    }, timeoutMs);
  });
  const call = httpSend(options, request, controller.signal);
  try {
    const raced = Promise.race([call, expiry]);
    call.catch(() => {});
    return await raced;
  } finally {
    clearTimeout(timer);
  }
}

// backoffDelayMs is exponential with full jitter: the constants are part
// of the cross-runtime parity contract and must match every other target.
export function backoffDelayMs(attempt: number, random: number): number {
  return random * Math.min(2000, 100 * 2 ** attempt);
}

// resolveMaxRetries clamps the operation's @retry field: a non-finite
// value or one below one both mean zero retries; a fractional value
// floors. bigint (an i64/u64-typed @retry field) narrows to a number
// first, the same conversion every other numeric ref narrows through.
export function resolveMaxRetries(value: number | bigint): number {
  const n = typeof value === "bigint" ? Number(value) : value;
  return Number.isFinite(n) && n >= 1 ? Math.floor(n) : 0;
}

// timingSeam is the sleep/random behind the retry loop's backoff, as a
// mutable object rather than fixed functions: an ES module import
// binding is read-only, so a plain `export function` could never be
// substituted from outside its own file, but a property of an
// exported object can. Internal to the package (this group is
// excluded from package.json's exports map), so only code shipped in
// the same SDK, never a consumer, can reach or override it. Math.random
// seeds only this jitter, never anything security-sensitive (no token,
// no session id, no cryptographic use), so a predictable PRNG default
// is fine.
export const timingSeam: {
  sleep: (ms: number) => Promise<void>;
  random: () => number;
} = {
  sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
  random: () => Math.random(), // NOSONAR: jitter timing only, not a cryptographic use
};

// retryDelay waits out one attempt's exponential-backoff delay before a
// retried call.
export async function retryDelay(attempt: number): Promise<void> {
  await timingSeam.sleep(backoffDelayMs(attempt, timingSeam.random()));
}
