// Code generated by tono. DO NOT EDIT.

export type Timestamp = string & { readonly __brand: "Timestamp" };

export type LocalDate = string & { readonly __brand: "LocalDate" };

export type Duration = string & { readonly __brand: "Duration" };

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  return BigInt(s);
}

export function encodeBytes(b: Uint8Array): string {
  return btoa(String.fromCharCode(...b));
}

export function decodeBytes(s: string): Uint8Array {
  return Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
}

export interface Charge {
  id: string;
  amount: bigint;
  fee: bigint;
  receipt: Uint8Array;
  currency: string;
  note?: string | null;
  tags: string[];
  metadata: Record<string, string>;
  created: Timestamp;
  status: Status;
  method: PaymentMethod;
}

export function encodeCharge(value: Charge): unknown {
  return {
    id: value.id,
    amount: encodeI64(value.amount),
    fee: encodeI64(value.fee),
    receipt: encodeBytes(value.receipt),
    currency: value.currency,
    note: value.note == null ? undefined : value.note,
    tags: value.tags.map((x) => x),
    metadata: Object.fromEntries(
      Object.entries(value.metadata).map(([k, v]) => [k, v]),
    ),
    created: value.created,
    status: encodeStatus(value.status),
    method: encodePaymentMethod(value.method),
  };
}

export function decodeCharge(raw: any): Charge {
  return {
    id: raw.id,
    amount: decodeI64(raw.amount),
    fee: decodeI64(raw.fee),
    receipt: decodeBytes(raw.receipt),
    currency: raw.currency,
    note: raw.note == null ? undefined : raw.note,
    tags: raw.tags.map((x: any) => x),
    metadata: Object.fromEntries(
      Object.entries(raw.metadata).map(([k, v]: [string, any]) => [k, v]),
    ),
    created: raw.created as Timestamp,
    status: decodeStatus(raw.status),
    method: decodePaymentMethod(raw.method),
  };
}

export type Status = "active" | "settled" | "refunded" | (string & {});

export function encodeStatus(value: Status): string {
  return value;
}

export function decodeStatus(raw: string): Status {
  return raw as Status;
}

export type HTTPCode = "ok" | "not_found" | "error" | (string & {});

export function encodeHTTPCode(value: HTTPCode): string {
  return value;
}

export function decodeHTTPCode(raw: string): HTTPCode {
  return raw as HTTPCode;
}

export interface Card {
  last4: string;
}

export function encodeCard(value: Card): unknown {
  return {
    last4: value.last4,
  };
}

export function decodeCard(raw: any): Card {
  return {
    last4: raw.last4,
  };
}

export interface BankAccount {
  iban: string;
}

export function encodeBankAccount(value: BankAccount): unknown {
  return {
    iban: value.iban,
  };
}

export function decodeBankAccount(raw: any): BankAccount {
  return {
    iban: raw.iban,
  };
}

export type PaymentMethod =
  | ({ kind: "card" } & Card)
  | ({ kind: "bank" } & BankAccount);

export function encodePaymentMethod(value: PaymentMethod): unknown {
  switch (value.kind) {
    case "card":
      return { kind: "card", ...(encodeCard(value as any) as object) };
    case "bank":
      return { kind: "bank", ...(encodeBankAccount(value as any) as object) };
  }
  throw new Error("unknown variant");
}

export function decodePaymentMethod(raw: any): PaymentMethod {
  switch (raw.kind) {
    case "card":
      return { kind: "card", ...(decodeCard(raw) as object) } as PaymentMethod;
    case "bank":
      return {
        kind: "bank",
        ...(decodeBankAccount(raw) as object),
      } as PaymentMethod;
  }
  throw new Error("unknown variant");
}
