// Code generated by tono. DO NOT EDIT.

export type Timestamp = string & { readonly __brand: "Timestamp" };

export type LocalDate = string & { readonly __brand: "LocalDate" };

export type Duration = string & { readonly __brand: "Duration" };

export interface Charge {
  id: string;
  amount: bigint;
  fee: bigint;
  receipt: Uint8Array;
  currency: string;
  note?: string | null;
  tags: string[];
  metadata: Record<string, string>;
  created: Timestamp;
  status: Status;
  method: PaymentMethod;
}

export type Status = "active" | "settled" | "refunded" | (string & {});

export type HTTPCode = 200 | 404 | 500 | (number & {});

export interface Card {
  last4: string;
}

export interface BankAccount {
  iban: string;
}

export type PaymentMethod =
  | ({ kind: "card" } & Card)
  | ({ kind: "bank" } & BankAccount);
