// Code generated by tono. DO NOT EDIT.

export type Timestamp = string & { readonly __brand: "Timestamp" };

export type LocalDate = string & { readonly __brand: "LocalDate" };

export type Duration = string & { readonly __brand: "Duration" };
