// Code generated by tono. DO NOT EDIT.

package tono

import "encoding/json"
import tonohttp "github.com/tono-lang/tono/runtimes/http-go"
import "time"

// MustDescriptor parses a compiler-emitted descriptor literal at package
// load; a parse failure is a build defect, never a runtime input.
func MustDescriptor(literal string) *tonohttp.WireDescriptor {
	d, err := tonohttp.ParseDescriptor([]byte(literal))
	if err != nil {
		panic(err)
	}
	return d
}

// EncodeRecord turns a typed input into the wire record the runtime binds
// from, through the type's own JSON tags.
func EncodeRecord(v any) (map[string]any, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	return m, nil
}

// DurationMs parses a duration field for the runtime's millisecond value
// positions.
func DurationMs(v string) (float64, error) {
	d, err := time.ParseDuration(v)
	if err != nil {
		return 0, err
	}
	return float64(d) / float64(time.Millisecond), nil
}
