// Code generated by tono. DO NOT EDIT.

package record

import "encoding/json"

// EncodeRecord turns a typed input into the wire record the runtime binds
// from, through the type's own JSON tags.
func EncodeRecord(v any) (map[string]any, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var m map[string]any
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	return m, nil
}
