// Code generated by tono. DO NOT EDIT.

import { durationToMs } from "../../duration";
import { readEnv } from "../../env";
import {
  assertExclusiveTransport,
  formatScalar,
  hasHeader,
  httpSend,
  httpSendWithTimeout,
  resolveMaxRetries,
  retryDelay,
  setHeader,
} from "../../http";
import {
  ClientOptions,
  Duration,
  HttpRequest,
  HttpResponse,
  HttpTransport,
} from "../../support";
import {
  decodeCardDeclined,
  decodeNotFound,
  encodeCharge,
  parseCharge,
} from "./codec";
import {
  APIError,
  CODE_CARD_DECLINED,
  CardDeclinedError,
  Charge,
  ConfigError,
  DecodeError,
  NotFoundError,
  STATUS_CARD_DECLINED,
  STATUS_NOT_FOUND,
  TonoError,
  TransportError,
  ValidationError,
  Violation,
  validateCharge,
} from "./types";

// Settings are the resolved construction values of the client entry.
// Exactly one transport slot may be set: fetch (native) or transport
// (canonical). headers are the base request headers; a declared @header
// wins only where nothing else set the name.
export interface Settings {
  apiKey: string;
  endpoint: string;
  timeout: Duration;
  maxRetries: number;
  fetch?: typeof fetch;
  transport?: HttpTransport;
  headers: Record<string, string>;
}

// ClientConfig carries the optional (@with) construction values of Client.
export interface ClientConfig {
  timeout?: Duration;
  maxRetries?: number;
}

function resolveSettingEndpoint(): string {
  {
    const v = readEnv("PAYMENTS_ENDPOINT");
    if (v !== undefined) {
      let parsed: string;
      parsed = v;
      return parsed;
    }
  }
  return "https://api.payments.example.com";
}

function resolveSettingTimeout(withValue: Duration | undefined): Duration {
  if (withValue !== undefined) return withValue;
  return "10s" as Duration;
}

function resolveSettingMaxRetries(withValue: number | undefined): number {
  if (withValue !== undefined) return withValue;
  return 2;
}

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares. The
// constructor takes the @arg values positionally and the @with values as a
// config object; construction resolves the declared sources, validates,
// and freezes the runtime options.
export class Client {
  private readonly settings: Settings;
  private readonly options: ClientOptions;
  private readonly timeoutMs: number;
  constructor(apiKey: string, config: ClientConfig = {}) {
    const s = Client.newSettings(apiKey, config);
    try {
      this.timeoutMs = durationToMs(String(s.timeout));
    } catch {
      throw new ConfigError(
        `timeout: invalid duration ${JSON.stringify(String(s.timeout))}`,
      );
    }
    this.settings = s;
    this.options = {
      fetch: s.fetch,
      transport: s.transport,
      headers: s.headers,
    };
    assertExclusiveTransport(this.options);
  }

  // newSettings resolves every construction value of Client that no foreign
  // call reaches, in declared order, then runs the consumed-chain requires
  // and the declared validation over them.
  private static newSettings(
    apiKey: string,
    config: ClientConfig = {},
  ): Settings {
    const s: Settings = {
      apiKey: "",
      endpoint: "",
      timeout: "" as Duration,
      maxRetries: 0,
      headers: {},
    };
    s.apiKey = apiKey;

    s.endpoint = resolveSettingEndpoint();

    s.timeout = resolveSettingTimeout(config.timeout);

    s.maxRetries = resolveSettingMaxRetries(config.maxRetries);

    const violations: Violation[] = [];
    if ([...s.apiKey].length < 1) {
      violations.push({
        field: "api_key",
        constraint: "length",
        message: "api_key length must be >= 1",
      });
    }
    if (violations.length > 0) {
      throw new ValidationError(violations);
    }
    return s;
  }

  async createCharge(input: Charge): Promise<Charge> {
    const invalid = validateCharge(input);
    if (invalid) {
      throw invalid;
    }
    const url = this.settings.endpoint + "/charges";

    const headers: Record<string, string> = {};
    setHeader(headers, "X-API-Key", formatScalar(this.settings.apiKey));
    for (const [k, v] of Object.entries(this.options.headers ?? {}))
      setHeader(headers, k, v);

    const body = JSON.stringify(encodeCharge(input));
    if (!hasHeader(headers, "content-type"))
      headers["content-type"] = "application/json";

    const timeoutMs = this.timeoutMs;

    const maxRetries = resolveMaxRetries(this.settings.maxRetries);

    for (let attempt = 0; ; attempt++) {
      const request: HttpRequest = {
        method: "POST",
        url,
        headers: { ...headers },
        body,
      };

      let response: HttpResponse;
      try {
        response = await httpSendWithTimeout(this.options, request, timeoutMs);
      } catch (cause) {
        if (attempt < maxRetries) {
          await retryDelay(attempt);
          continue;
        }
        throw new TransportError(cause);
      }
      const outcome = response;

      if (response.status === 201) {
        try {
          return parseCharge(outcome.body);
        } catch (path) {
          throw new DecodeError(path as string, "Charge", outcome.body);
        }
      }

      const err = decodeCreateChargeError(outcome.status, outcome.body);
      if (attempt < maxRetries && err.retryable()) {
        await retryDelay(attempt);
        continue;
      }
      throw err;
    }
  }
  async latestCharge(): Promise<Charge | null> {
    const url = this.settings.endpoint + "/charges/latest";

    const headers: Record<string, string> = {};
    setHeader(headers, "X-API-Key", formatScalar(this.settings.apiKey));
    for (const [k, v] of Object.entries(this.options.headers ?? {}))
      setHeader(headers, k, v);

    const request: HttpRequest = {
      method: "GET",
      url,
      headers: { ...headers },
      body: undefined,
    };

    let response: HttpResponse;
    try {
      response = await httpSend(this.options, request, undefined);
    } catch (cause) {
      throw new TransportError(cause);
    }
    const outcome = response;

    if (response.status >= 200 && response.status < 300) {
      const rawBody = outcome.body.trim();
      if (rawBody === "" || rawBody === "null") {
        return null;
      }
      try {
        return parseCharge(outcome.body);
      } catch (path) {
        throw new DecodeError(path as string, "Charge", outcome.body);
      }
    }

    throw new APIError(outcome.status, outcome.body);
  }
}

export function decodeCreateChargeError(
  status: number,
  body: string,
): TonoError {
  let parsed: any;
  try {
    // A body that fails to parse falls straight to the fallback, which
    // carries the raw body as APIError.
    parsed = JSON.parse(body);
  } catch {
    return new APIError(status, body);
  }
  try {
    if (
      status === STATUS_CARD_DECLINED &&
      parsed?.["code"] === CODE_CARD_DECLINED
    ) {
      return new CardDeclinedError(decodeCardDeclined(parsed), body);
    }
    if (status === STATUS_NOT_FOUND) {
      return new NotFoundError(decodeNotFound(parsed), body);
    }
  } catch {}
  return new APIError(status, body);
}
