// Code generated by tono. DO NOT EDIT.

import { durationToMs } from "../../duration";
import { readEnv } from "../../env";
import {
  assertExclusiveTransport,
  backoffDelayMs,
  defaultRandom,
  defaultSleep,
  hasHeader,
  httpSendWithTimeout,
  resolveMaxRetries,
  resolveTimeoutMs,
  setHeader,
} from "../../http";
import {
  ClientOptions,
  Duration,
  HttpRequest,
  HttpResponse,
  HttpTransport,
} from "../../support";
import {
  decodeCardDeclined,
  decodeNotFound,
  encodeCharge,
  parseCharge,
} from "./codec";
import {
  APIError,
  CODE_CARD_DECLINED,
  CardDeclinedError,
  Charge,
  ConfigError,
  DecodeError,
  NotFoundError,
  STATUS_CARD_DECLINED,
  STATUS_NOT_FOUND,
  TonoError,
  TransportError,
  ValidationError,
  Violation,
  validateCharge,
} from "./types";

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: fetch (native) or transport
// (canonical). headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
export interface Settings {
  apiKey: string;
  endpoint: string;
  timeout: Duration;
  maxRetries: number;
  fetch?: typeof fetch;
  transport?: HttpTransport;
  headers: Record<string, string>;
}

// ClientConfig carries the optional (@with) construction values of Client.
export interface ClientConfig {
  timeout?: Duration;
  maxRetries?: number;
}

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares. The
// constructor takes the @arg values positionally and the @with values as a
// config object; construction resolves the declared sources, runs the
// client_init bridge, validates, and freezes the runtime options.
export class Client {
  private readonly settings: Settings;
  private readonly options: ClientOptions;
  constructor(apiKey: string, config: ClientConfig = {}) {
    const s: Settings = {
      apiKey: "",
      endpoint: "",
      timeout: "" as Duration,
      maxRetries: 0,
      headers: {},
    };
    s.apiKey = apiKey;
    let endpointSet = false;
    if (!endpointSet) {
      const v = readEnv("PAYMENTS_ENDPOINT");
      if (v !== undefined) {
        s.endpoint = v;
        endpointSet = true;
      }
    }
    if (!endpointSet) {
      s.endpoint = "https://api.payments.example.com";
    }
    let timeoutSet = false;
    if (!timeoutSet && config.timeout !== undefined) {
      s.timeout = config.timeout;
      timeoutSet = true;
    }
    if (!timeoutSet) {
      s.timeout = "10s" as Duration;
    }
    let maxRetriesSet = false;
    if (!maxRetriesSet && config.maxRetries !== undefined) {
      s.maxRetries = config.maxRetries;
      maxRetriesSet = true;
    }
    if (!maxRetriesSet) {
      s.maxRetries = 2;
    }
    const violations: Violation[] = [];
    if ([...s.apiKey].length < 1) {
      violations.push({
        field: "api_key",
        constraint: "length",
        message: "api_key length must be >= 1",
      });
    }
    if (violations.length > 0) {
      throw new ValidationError(violations);
    }
    const values: Record<string, unknown> = {};
    values["api_key"] = s.apiKey;
    values["endpoint"] = s.endpoint;
    try {
      values["timeout"] = durationToMs(String(s.timeout));
    } catch {
      throw new ConfigError(
        `timeout: invalid duration ${JSON.stringify(String(s.timeout))}`,
      );
    }
    values["max_retries"] = s.maxRetries;
    this.settings = s;
    this.options = {
      baseUrl: "",
      fetch: s.fetch,
      transport: s.transport,
      headers: s.headers,
      values,
    };
    assertExclusiveTransport(this.options);
  }

  // forTest is the constructor plus the transport seam the generated
  // tests construct through: the real construction path runs first, then
  // the canonical transport wins over anything bespoke.
  static forTest(
    seam: { transport: HttpTransport },
    apiKey: string,
    config: ClientConfig = {},
  ): Client {
    const client = new Client(apiKey, config);
    const options = client.options as {
      transport?: HttpTransport;
      fetch?: typeof fetch;
    };
    options.transport = seam.transport;
    options.fetch = undefined;
    return client;
  }

  async createCharge(input: Charge): Promise<Charge> {
    const invalid = validateCharge(input);
    if (invalid) {
      throw invalid;
    }
    const record = encodeCharge(input) as unknown as Record<string, unknown>;
    const url =
      (typeof this.options.values?.["endpoint"] === "string" &&
      this.options.values?.["endpoint"] !== ""
        ? (this.options.values?.["endpoint"] as string)
        : this.options.baseUrl) + "/charges";
    const headers: Record<string, string> = {};
    setHeader(
      headers,
      "X-API-Key",
      String(this.options.values?.["api_key"] ?? ""),
    );
    for (const [k, v] of Object.entries(this.options.headers ?? {}))
      setHeader(headers, k, v);
    const body = JSON.stringify({
      amount: record["amount"],
      created: record["created"],
      currency: record["currency"],
      fee: record["fee"],
      id: record["id"],
      metadata: record["metadata"],
      method: record["method"],
      note: record["note"],
      receipt: record["receipt"],
      status: record["status"],
      tags: record["tags"],
    });
    if (!hasHeader(headers, "content-type"))
      headers["content-type"] = "application/json";
    const timeoutMs = resolveTimeoutMs(this.options.values?.["timeout"]);
    const maxRetries = resolveMaxRetries(this.options.values?.["max_retries"]);
    for (let attempt = 0; ; attempt++) {
      const request: HttpRequest = {
        method: "POST",
        url,
        headers: { ...headers },
        body,
      };
      let response: HttpResponse;
      try {
        response = await httpSendWithTimeout(this.options, request, timeoutMs);
      } catch (cause) {
        if (attempt >= maxRetries) {
          throw new TransportError(cause);
        }
        await defaultSleep(backoffDelayMs(attempt, defaultRandom()));
        continue;
      }
      const outcome = { status: response.status, body: response.body };
      if (!(response.status >= 200 && response.status < 300)) {
        const err = decodeCreateChargeError(outcome.status, outcome.body);
        if (attempt < maxRetries && err.retryable()) {
          await defaultSleep(backoffDelayMs(attempt, defaultRandom()));
          continue;
        }
        throw err;
      }
      try {
        return parseCharge(outcome.body);
      } catch (path) {
        throw new DecodeError(path as string, "Charge", outcome.body);
      }
    }
  }
}

export function decodeCreateChargeError(
  status: number,
  body: string,
): TonoError {
  let parsed: any;
  try {
    parsed = JSON.parse(body);
  } catch {
    return new APIError(status, body);
  }
  const code =
    typeof parsed === "object" && parsed !== null ? parsed["code"] : undefined;
  try {
    if (status === STATUS_CARD_DECLINED && code === CODE_CARD_DECLINED) {
      return new CardDeclinedError(decodeCardDeclined(parsed), body);
    }
    if (status === STATUS_NOT_FOUND) {
      return new NotFoundError(decodeNotFound(parsed), body);
    }
  } catch {}
  return new APIError(status, body);
}
