// Code generated by tono. DO NOT EDIT.

import { durationToMs, readEnv } from "../../internal/tono";
import { Duration } from "../../support";
import {
  CanonicalTransport,
  ClientOptions,
  WireDescriptor,
  assertExclusiveTransport,
  execute,
} from "@tono/http-runtime-ts";
import {
  decodeCardDeclined,
  decodeCharge,
  decodeNotFound,
  encodeCharge,
} from "./codec";
import {
  APIError,
  CardDeclinedError,
  Charge,
  ConfigError,
  DecodeError,
  NotFoundError,
  TonoError,
  TransportError,
  ValidationError,
  Violation,
  validateCharge,
} from "./types";

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: fetch (native) or transport
// (canonical). headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
export interface Settings {
  apiKey: string;
  endpoint: string;
  timeout: Duration;
  maxRetries: number;
  fetch?: typeof fetch;
  transport?: CanonicalTransport;
  headers: Record<string, string>;
}

// ClientConfig carries the optional (@with) construction values of Client.
export interface ClientConfig {
  timeout?: Duration;
  maxRetries?: number;
}

const createChargeDescriptor: WireDescriptor = JSON.parse(
  '{"bindings":[["id",{"kind":"body"}],["amount",{"kind":"body"}],["fee",{"kind":"body"}],["receipt",{"kind":"body"}],["currency",{"kind":"body"}],["note",{"kind":"body"}],["tags",{"kind":"body"}],["metadata",{"kind":"body"}],["created",{"kind":"body"}],["status",{"kind":"body"}],["method",{"kind":"body"}]],"endpoint":["endpoint"],"errors":[[402,"payments.charges#card_declined","card_declined",true],[404,"payments.charges#not_found",null]],"http_method":"POST","request_headers":[[[{"lit":"X-API-Key"}],{"field":["api_key"]}]],"response_bindings":[],"retry":{"max":{"ref":"max_retries"}},"success":[[200,{"args":[],"ref":"payments.charges#charge"}]],"timeout":{"ref":"timeout"},"uri":"/charges"}',
);

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares. The
// constructor takes the @arg values positionally and the @with values as a
// config object; construction resolves the declared sources, runs the
// client_init bridge, validates, and freezes the runtime options.
export class Client {
  private readonly settings: Settings;
  private readonly options: ClientOptions;
  constructor(apiKey: string, config: ClientConfig = {}) {
    const s: Settings = {
      apiKey: "",
      endpoint: "",
      timeout: "" as Duration,
      maxRetries: 0,
      headers: {},
    };
    s.apiKey = apiKey;
    let endpointSet = false;
    if (!endpointSet) {
      const v = readEnv("PAYMENTS_ENDPOINT");
      if (v !== undefined) {
        s.endpoint = v;
        endpointSet = true;
      }
    }
    if (!endpointSet) {
      s.endpoint = "https://api.payments.example.com";
    }
    let timeoutSet = false;
    if (!timeoutSet && config.timeout !== undefined) {
      s.timeout = config.timeout;
      timeoutSet = true;
    }
    if (!timeoutSet) {
      s.timeout = "10s" as Duration;
    }
    let maxRetriesSet = false;
    if (!maxRetriesSet && config.maxRetries !== undefined) {
      s.maxRetries = config.maxRetries;
      maxRetriesSet = true;
    }
    if (!maxRetriesSet) {
      s.maxRetries = 2;
    }
    const violations: Violation[] = [];
    if ([...s.apiKey].length < 1) {
      violations.push({
        field: "api_key",
        constraint: "length",
        message: "api_key length must be >= 1",
      });
    }
    if (violations.length > 0) {
      throw new ValidationError(violations);
    }
    const values: Record<string, unknown> = {};
    values["api_key"] = s.apiKey;
    values["endpoint"] = s.endpoint;
    try {
      values["timeout"] = durationToMs(String(s.timeout));
    } catch {
      throw new ConfigError(
        `timeout: invalid duration ${JSON.stringify(String(s.timeout))}`,
      );
    }
    values["max_retries"] = s.maxRetries;
    this.settings = s;
    this.options = {
      baseUrl: "",
      fetch: s.fetch,
      transport: s.transport,
      headers: s.headers,
      values,
    };
    assertExclusiveTransport(this.options);
  }

  async createCharge(input: Charge): Promise<Charge> {
    const invalid = validateCharge(input);
    if (invalid) {
      throw invalid;
    }
    const outcome = await execute(
      createChargeDescriptor,
      encodeCharge(input),
      this.options,
    );
    if (outcome.outcome === "transport") {
      throw new TransportError(outcome.cause);
    }
    if (outcome.outcome === "error") {
      throw decodeCreateChargeError(outcome.status, outcome.body);
    }
    let raw: any;
    try {
      raw = JSON.parse(outcome.body);
    } catch {
      throw new DecodeError("$", "Charge", outcome.body);
    }
    if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
      throw new DecodeError("$", "Charge", outcome.body);
    }
    if (!("id" in raw) || raw["id"] === null) {
      throw new DecodeError("$.id", "Charge", outcome.body);
    }
    if (!("amount" in raw) || raw["amount"] === null) {
      throw new DecodeError("$.amount", "Charge", outcome.body);
    }
    if (!("fee" in raw) || raw["fee"] === null) {
      throw new DecodeError("$.fee", "Charge", outcome.body);
    }
    if (!("receipt" in raw) || raw["receipt"] === null) {
      throw new DecodeError("$.receipt", "Charge", outcome.body);
    }
    if (!("currency" in raw) || raw["currency"] === null) {
      throw new DecodeError("$.currency", "Charge", outcome.body);
    }
    if (!("tags" in raw) || raw["tags"] === null) {
      throw new DecodeError("$.tags", "Charge", outcome.body);
    }
    if (!("metadata" in raw) || raw["metadata"] === null) {
      throw new DecodeError("$.metadata", "Charge", outcome.body);
    }
    if (!("created" in raw) || raw["created"] === null) {
      throw new DecodeError("$.created", "Charge", outcome.body);
    }
    if (!("status" in raw) || raw["status"] === null) {
      throw new DecodeError("$.status", "Charge", outcome.body);
    }
    if (!("method" in raw) || raw["method"] === null) {
      throw new DecodeError("$.method", "Charge", outcome.body);
    }
    let out: Charge;
    try {
      out = decodeCharge(raw);
    } catch {
      throw new DecodeError("$", "Charge", outcome.body);
    }
    return out;
  }
}

export function decodeCreateChargeError(
  status: number,
  body: string,
): TonoError {
  let parsed: any;
  try {
    parsed = JSON.parse(body);
  } catch {
    return new APIError(status, body);
  }
  const code =
    typeof parsed === "object" && parsed !== null ? parsed["code"] : undefined;
  try {
    if (status === 402 && code === "card_declined") {
      return new CardDeclinedError(decodeCardDeclined(parsed), body);
    }
    if (status === 404) {
      return new NotFoundError(decodeNotFound(parsed), body);
    }
  } catch {}
  return new APIError(status, body);
}
