// Code generated by tono. DO NOT EDIT.

import { Client } from "./client";
import { ValidationError } from "./types";
import { describe, expect, it } from "vitest";

// The ambient process env, reached through globalThis so the generated
// test does not require node type declarations.
const vectorEnv: Record<string, string | undefined> =
  (globalThis as { process?: { env?: Record<string, string | undefined> } })
    .process?.env ?? {};

describe("client", () => {
  it("construction rejects an empty api key", async () => {
    const prevEnv: Record<string, string | undefined> = {
      PAYMENTS_ENDPOINT: vectorEnv["PAYMENTS_ENDPOINT"],
    };
    delete vectorEnv["PAYMENTS_ENDPOINT"];
    try {
      let caught: unknown;
      try {
        new Client("");
      } catch (e) {
        caught = e;
      }
      expect(caught).toBeInstanceOf(ValidationError);
      expect(
        (caught as ValidationError).violations.map((x) => x.field),
      ).toEqual(["api_key"]);
    } finally {
      for (const [name, value] of Object.entries(prevEnv)) {
        if (value === undefined) {
          delete vectorEnv[name];
        } else {
          vectorEnv[name] = value;
        }
      }
    }
  });
});
