// Code generated by tono. DO NOT EDIT.

import {
  decodeBytes,
  decodeI64,
  decodeU64,
  encodeBytes,
  encodeI64,
} from "../../internal/codec";
import { Timestamp } from "../../support";
import { CardDeclined, Charge, NotFound } from "./types";
import {
  decodePaymentMethod,
  decodeStatus,
  encodePaymentMethod,
  encodeStatus,
} from "../common/codec";

export function encodeCharge(value: Charge): unknown {
  return {
    id: value.id,
    amount: encodeI64(value.amount),
    fee: encodeI64(value.fee),
    receipt: encodeBytes(value.receipt),
    currency: value.currency,
    note: value.note == null ? undefined : value.note,
    tags: value.tags.map((x) => x),
    metadata: Object.fromEntries(
      Object.entries(value.metadata).map(([k, v]) => [k, v]),
    ),
    created: value.created,
    status: encodeStatus(value.status),
    method: encodePaymentMethod(value.method),
  };
}

export function decodeCharge(raw: any): Charge {
  return {
    id: raw.id,
    amount: decodeI64(raw.amount),
    fee: decodeU64(raw.fee),
    receipt: decodeBytes(raw.receipt),
    currency: raw.currency,
    note: raw.note == null ? undefined : raw.note,
    tags: raw.tags.map((x: any) => x),
    metadata: Object.fromEntries(
      Object.entries(raw.metadata).map(([k, v]: [string, any]) => [k, v]),
    ),
    created: raw.created as Timestamp,
    status: decodeStatus(raw.status),
    method: decodePaymentMethod(raw.method),
  };
}

export function encodeCardDeclined(value: CardDeclined): unknown {
  return {
    message: value.message,
  };
}

export function decodeCardDeclined(raw: any): CardDeclined {
  return {
    message: raw.message,
  };
}

export function encodeNotFound(value: NotFound): unknown {
  return {
    message: value.message,
  };
}

export function decodeNotFound(raw: any): NotFound {
  return {
    message: raw.message,
  };
}
