// Code generated by tono. DO NOT EDIT.

import { decodeBytes, encodeBytes } from "../../bytes";
import { decodeI64, decodeU64, encodeI64 } from "../../number";
import { Timestamp } from "../../support";
import { CardDeclined, Charge, NotFound } from "./types";
import {
  decodePaymentMethod,
  decodeStatus,
  encodePaymentMethod,
  encodeStatus,
} from "../common/codec";

export function encodeCharge(value: Charge): unknown {
  return {
    id: value.id,
    amount: encodeI64(value.amount),
    fee: encodeI64(value.fee),
    receipt: encodeBytes(value.receipt),
    currency: value.currency,
    note: value.note == null ? undefined : value.note,
    tags: value.tags.map((x) => x),
    metadata: Object.fromEntries(
      Object.entries(value.metadata).map(([k, v]) => [k, v]),
    ),
    created: value.created,
    status: encodeStatus(value.status),
    method: encodePaymentMethod(value.method),
  };
}

export function decodeCharge(raw: any): Charge {
  return {
    id: raw.id,
    amount: decodeI64(raw.amount),
    fee: decodeU64(raw.fee),
    receipt: decodeBytes(raw.receipt),
    currency: raw.currency,
    note: raw.note == null ? undefined : raw.note,
    tags: raw.tags.map((x: any) => x),
    metadata: Object.fromEntries(
      Object.entries(raw.metadata).map(([k, v]: [string, any]) => [k, v]),
    ),
    created: raw.created as Timestamp,
    status: decodeStatus(raw.status),
    method: decodePaymentMethod(raw.method),
  };
}

export function decodeCardDeclined(raw: any): CardDeclined {
  return {
    message: raw.message,
  };
}

export function decodeNotFound(raw: any): NotFound {
  return {
    message: raw.message,
  };
}

/** The members Charge's declared shape requires present. */
const chargeRequiredFields = [
  "id",
  "amount",
  "fee",
  "receipt",
  "currency",
  "tags",
  "metadata",
  "created",
  "status",
  "method",
] as const;

/**
 * Parses a Charge from its wire JSON: every required member must be
 * present (a null value counts as absent) before the typed decode
 * runs. Throws the failed path (`$` for the whole body, `$.field` for
 * a missing member) as a plain string, for the caller to build its
 * own DecodeError.
 */
export function parseCharge(raw: string): Charge {
  let obj: any;
  try {
    obj = JSON.parse(raw);
  } catch {
    throw "$";
  }
  if (typeof obj !== "object" || obj === null || Array.isArray(obj)) {
    throw "$";
  }
  for (const field of chargeRequiredFields) {
    if (!(field in obj) || obj[field] === null) {
      throw "$." + field;
    }
  }
  return decodeCharge(obj);
}
