// Code generated by tono. DO NOT EDIT.

import { Timestamp } from "../../support";
import { PaymentMethod, Status } from "../common/types";

/** A small payments API that exercises the hard wire cases end to end. */
export interface Charge {
  id: string;
  amount: bigint;
  /** @deprecated folded into amount */
  fee: bigint;
  receipt: Uint8Array;
  currency: string;
  note?: string | null;
  tags: string[];
  metadata: Record<string, string>;
  created: Timestamp;
  status: Status;
  method: PaymentMethod;
}

export function validateCharge(value: Charge): ValidationError | null {
  const violations: Violation[] = [];
  if (value.amount < 0n) {
    violations.push({
      field: "amount",
      constraint: "range",
      message: "amount must be >= 0",
    });
  }
  if ([...value.currency].length < 3) {
    violations.push({
      field: "currency",
      constraint: "length",
      message: "currency length must be >= 3",
    });
  }
  if ([...value.currency].length > 3) {
    violations.push({
      field: "currency",
      constraint: "length",
      message: "currency length must be <= 3",
    });
  }
  return violations.length > 0 ? new ValidationError(violations) : null;
}

/** The card issuer declined the charge. */
export interface CardDeclined {
  message: string;
}

/** No charge exists for the requested id. */
export interface NotFound {
  message: string;
}

export abstract class TonoError extends Error {
  retryable(): boolean {
    return false;
  }
}

export interface Violation {
  field: string;
  constraint: string;
  message: string;
}

export class ValidationError extends TonoError {
  constructor(readonly violations: Violation[]) {
    super("validation failed");
    this.name = "ValidationError";
  }
}

export class TransportError extends TonoError {
  constructor(readonly cause: unknown) {
    super("transport failure");
    this.name = "TransportError";
  }
}

export class DecodeError extends TonoError {
  constructor(
    readonly path: string,
    readonly expected: string,
    readonly raw: string,
  ) {
    super("response body did not match the declared schema");
    this.name = "DecodeError";
  }
}

export class APIError extends TonoError {
  constructor(
    readonly status: number,
    readonly body: string,
  ) {
    super(`api error ${status}`);
    this.name = "APIError";
  }
}

export class ConfigError extends TonoError {
  constructor(
    message: string,
    readonly cause?: unknown,
  ) {
    super(message);
    this.name = "ConfigError";
  }
}

export const STATUS_CARD_DECLINED = 402;

export const CODE_CARD_DECLINED = "card_declined";

export class CardDeclinedError extends APIError {
  constructor(
    readonly data: CardDeclined,
    body: string,
  ) {
    super(STATUS_CARD_DECLINED, body);
    this.name = "CardDeclinedError";
  }
  retryable(): boolean {
    return true;
  }
}

export const STATUS_NOT_FOUND = 404;

export class NotFoundError extends APIError {
  constructor(
    readonly data: NotFound,
    body: string,
  ) {
    super(STATUS_NOT_FOUND, body);
    this.name = "NotFoundError";
  }
}
export type HTTPCode = 200 | 404 | 500 | (number & {});

export function encodeHTTPCode(value: HTTPCode): number {
  return value;
}

export function decodeHTTPCode(raw: number): HTTPCode {
  return raw as HTTPCode;
}

/** A page of results with an optional continuation cursor. */
export interface Page<T> {
  items: T[];
  nextCursor?: string | null;
}
