// Code generated by tono. DO NOT EDIT.

package descriptor

import tonohttp "github.com/tono-lang/tono/runtimes/http-go"

// MustDescriptor parses a compiler-emitted descriptor literal at package
// load; a parse failure is a build defect, never a runtime input.
func MustDescriptor(literal string) *tonohttp.WireDescriptor {
	d, err := tonohttp.ParseDescriptor([]byte(literal))
	if err != nil {
		panic(err)
	}
	return d
}
