// Code generated by tono. DO NOT EDIT.

package transport

import (
	"bytes"
	"context"
	"example.com/sdk/support"
	"io"
	"math"
	"math/rand"
	"net/http"
	"strings"
	"time"
)

// Request is one operation's HTTP call as the generated client assembled
// it: the finished URL, the layered headers, and the encoded body, plus
// the operation's declared call policy.
type Request struct {
	Method  string
	URL     string
	Headers map[string]string
	// Body is the encoded request body; nil sends none.
	Body []byte
	// Timeout bounds each attempt separately, as a context deadline around
	// the dispatch; zero means no deadline.
	Timeout time.Duration
	// Retry is the operation's declared retry policy; the zero value never
	// retries.
	Retry Retry
	// Success lists the operation's declared success statuses outside the
	// 2xx range (any 2xx always counts), so the retry loop never retries a
	// response the operation treats as a success.
	Success []int
	// Timing is the clock behind the retry backoff; the zero value uses the
	// real clock and jitter.
	Timing Timing
}

// Retry is an operation's declared retry policy: Max retries beyond the
// first attempt, and When classifying an error response (status and raw
// body) as retryable. A transport failure always retries while attempts
// remain; a nil When means no error response ever does.
type Retry struct {
	Max  int
	When func(status int, body string) bool
}

// Timing is the clock behind the retry backoff, swappable so a test can
// pin the jitter and record the sleeps instead of waiting them out. The
// generated client holds one in an unexported field, which is what keeps
// the seam reachable from its own package's tests and from nowhere else.
type Timing struct {
	Sleep  func(ctx context.Context, d time.Duration) error
	Random func() float64
}

// retryable classifies one outcome for the retry loop: a transport failure
// always retries; a success never does; an error response only when
// Retry.When accepts its status and raw body.
func retryable(o Outcome, req Request) bool {
	if o.Cause != nil {
		return true
	}
	if isSuccess(o.Status, req.Success) || req.Retry.When == nil {
		return false
	}
	return req.Retry.When(o.Status, o.Body)
}

// isSuccess: any 2xx is a success even when its exact code was not the one
// declared (a server may answer 200 where 201 was declared); a declared
// success code outside the 2xx range still counts.
func isSuccess(status int, declared []int) bool {
	if status >= 200 && status < 300 {
		return true
	}
	for _, s := range declared {
		if s == status {
			return true
		}
	}
	return false
}

// backoffDelay is exponential with full jitter: random * min(2000ms, 100ms
// * 2^attempt). The constants are part of the cross-runtime parity
// contract and must match every other target.
func backoffDelay(attempt int, random float64) time.Duration {
	exp := math.Min(2000, 100*math.Pow(2, float64(attempt)))
	return time.Duration(random * exp * float64(time.Millisecond))
}

// retryDelay waits out one attempt's backoff, on the request's timing seam
// when a test pinned it and the real clock otherwise. Jitter seeds only
// this backoff, never anything security-sensitive, so the default PRNG is
// fine.
func retryDelay(ctx context.Context, attempt int, timing Timing) error {
	random := timing.Random
	if random == nil {
		random = rand.Float64
	}
	sleep := timing.Sleep
	if sleep == nil {
		sleep = sleepContext
	}
	return sleep(ctx, backoffDelay(attempt, random()))
}

func sleepContext(ctx context.Context, d time.Duration) error {
	timer := time.NewTimer(d)
	defer timer.Stop()
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

// Outcome is the raw result of one call: a response's status, headers, and
// body, or the transport failure that prevented one (Cause non-nil). The
// generated client maps it onto its own error taxonomy; this package stays
// taxonomy-free so every module can share it.
type Outcome struct {
	Status  int
	Headers map[string]string
	Body    string
	Cause   error
}

// Send performs one operation call: per attempt, one dispatch
// against the configured transport.
// A retryable outcome (a transport failure, or an error response
// Retry.When accepts) repeats up to Retry.Max times, with exponential
// full-jitter backoff between attempts.
func Send(ctx context.Context, native *http.Client, canonical support.HTTPTransport, req Request) (Outcome, error) {
	for attempt := 0; ; attempt++ {
		outcome, err := sendOnce(ctx, native, canonical, req)
		if err != nil {
			return Outcome{}, err
		}
		if attempt >= req.Retry.Max || !retryable(outcome, req) {
			return outcome, nil
		}
		if err := retryDelay(ctx, attempt, req.Timing); err != nil {
			// The caller gave up while we were waiting to retry: surface the
			// cancellation, not the stale outcome it interrupts.
			return Outcome{Cause: err}, nil
		}
	}
}

// sendOnce is one attempt of [Send].
func sendOnce(ctx context.Context, native *http.Client, canonical support.HTTPTransport, req Request) (Outcome, error) {
	headers := make(map[string]string, len(req.Headers))
	for name, value := range req.Headers {
		headers[name] = value
	}
	request := support.HTTPRequest{Method: req.Method, URL: req.URL, Headers: headers, Body: req.Body}
	// The deadline covers the dispatch (transport call and body read) only.
	attemptCtx := ctx
	if req.Timeout > 0 {
		var cancel context.CancelFunc
		attemptCtx, cancel = context.WithTimeout(ctx, req.Timeout)
		defer cancel()
	}
	response, err := dispatch(attemptCtx, native, canonical, request)
	if err != nil {
		return Outcome{Cause: err}, nil
	}
	return Outcome{Status: response.Status, Headers: response.Headers, Body: response.Body}, nil
}

// dispatch performs the raw exchange: the canonical transport when set, the
// native client otherwise (http.DefaultClient when neither).
func dispatch(ctx context.Context, native *http.Client, canonical support.HTTPTransport, req support.HTTPRequest) (support.HTTPResponse, error) {
	if canonical != nil {
		return canonical(ctx, req)
	}
	client := native
	if client == nil {
		client = http.DefaultClient
	}
	var reader io.Reader
	if req.Body != nil {
		reader = bytes.NewReader(req.Body)
	}
	httpReq, err := http.NewRequestWithContext(ctx, req.Method, req.URL, reader)
	if err != nil {
		return support.HTTPResponse{}, err
	}
	for name, value := range req.Headers {
		httpReq.Header.Set(name, value)
	}
	httpRes, err := client.Do(httpReq)
	if err != nil {
		return support.HTTPResponse{}, err
	}
	defer httpRes.Body.Close()
	// The body read can fail mid-stream too, so it shares the transport error
	// path.
	data, err := io.ReadAll(httpRes.Body)
	if err != nil {
		return support.HTTPResponse{}, err
	}
	headers := make(map[string]string, len(httpRes.Header))
	for name := range httpRes.Header {
		headers[strings.ToLower(name)] = httpRes.Header.Get(name)
	}
	return support.HTTPResponse{Status: httpRes.StatusCode, Headers: headers, Body: string(data)}, nil
}

// SetHeader overrides across casings: header names are case-insensitive,
// so a bespoke "authorization" replaces a declared "Authorization" rather
// than riding beside it.
func SetHeader(headers map[string]string, name, value string) {
	for key := range headers {
		if strings.EqualFold(key, name) {
			delete(headers, key)
		}
	}
	headers[name] = value
}

// HasHeader reports whether a header is already set under any casing: a
// caller-supplied "Content-Type" must suppress the default rather than
// sit beside a second "content-type".
func HasHeader(headers map[string]string, name string) bool {
	for key := range headers {
		if strings.EqualFold(key, name) {
			return true
		}
	}
	return false
}
