// Code generated by tono. DO NOT EDIT.

pub fn entry_transform_words(s: &str) -> Vec<&str> {
    s.split(|c: char| c == ' ' || c == '-' || c == '_')
        .filter(|w| !w.is_empty())
        .collect()
}

#[allow(non_snake_case)]
pub fn strUpperSnake(s: String) -> String {
    entry_transform_words(&s)
        .iter()
        .map(|w| w.to_uppercase())
        .collect::<Vec<_>>()
        .join("_")
}

#[allow(non_snake_case)]
pub fn strSnake(s: String) -> String {
    entry_transform_words(&s)
        .iter()
        .map(|w| w.to_lowercase())
        .collect::<Vec<_>>()
        .join("_")
}

#[allow(non_snake_case)]
pub fn strKebab(s: String) -> String {
    entry_transform_words(&s)
        .iter()
        .map(|w| w.to_lowercase())
        .collect::<Vec<_>>()
        .join("-")
}

#[allow(non_snake_case)]
pub fn strPascal(s: String) -> String {
    entry_transform_words(&s)
        .iter()
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + &c.as_str().to_lowercase(),
                None => String::new(),
            }
        })
        .collect::<String>()
}
