// Code generated by tono. DO NOT EDIT.

use crate::support::{BoxFuture, ClientOptions, HttpError, HttpRequest, HttpResponse};

/// Overrides across casings: header names are case-insensitive, so a
/// bespoke "authorization" replaces a declared "Authorization" rather
/// than riding beside it.
pub fn set_header(
    headers: &mut std::collections::HashMap<String, String>,
    name: &str,
    value: String,
) {
    headers.retain(|k, _| !k.eq_ignore_ascii_case(name));
    headers.insert(name.to_string(), value);
}

/// Whether a header is already set under any casing: a caller-supplied
/// "Content-Type" must suppress the default rather than sit beside a
/// second "content-type".
pub fn has_header(headers: &std::collections::HashMap<String, String>, name: &str) -> bool {
    headers.keys().any(|k| k.eq_ignore_ascii_case(name))
}

/// Exponential backoff with full jitter: the constants are part of the
/// cross-runtime parity contract and must match every other target.
pub fn backoff_delay_ms(attempt: u32, random: f64) -> f64 {
    random * 2000f64.min(100.0 * 2f64.powi(attempt as i32))
}

/// Clamps the operation's `@retry` field, which the frontend types as
/// an integer scalar: a value below one means zero retries.
pub fn resolve_max_retries(value: i64) -> u32 {
    value.clamp(0, u32::MAX as i64) as u32
}

pub fn default_sleep() -> SleepFn {
    std::sync::Arc::new(|ms: f64| {
        Box::pin(tokio::time::sleep(std::time::Duration::from_secs_f64(
            ms.max(0.0) / 1000.0,
        )))
    })
}

/// The jitter source behind the backoff, swappable like the sleep.
pub type RandomFn = std::sync::Arc<dyn Fn() -> f64 + Send + Sync>;

/// A "random-enough" `[0, 1)` value for backoff jitter, drawn from the
/// standard library's per-process random seed (no `rand` dependency;
/// jitter has no security requirement, and the parity harness always
/// pins the seam).
pub fn default_random() -> RandomFn {
    std::sync::Arc::new(|| {
        use std::collections::hash_map::RandomState;
        use std::hash::{BuildHasher, Hasher};
        let seed = RandomState::new().build_hasher().finish();
        (seed as f64 / u64::MAX as f64).min(0.999_999_999)
    })
}

/// Rejects an unusable transport configuration at construction time:
/// with the `reqwest` feature on, setting both slots is ambiguous;
/// with it off, the canonical slot is the only way to send at all.
#[cfg(feature = "reqwest")]
pub fn check_transport(options: &ClientOptions) -> Result<(), String> {
    if options.client.is_some() && options.transport.is_some() {
        return Err("Settings.client and Settings.transport are mutually exclusive: set the native slot or the canonical slot, not both".to_string());
    }
    Ok(())
}
#[cfg(not(feature = "reqwest"))]
pub fn check_transport(options: &ClientOptions) -> Result<(), String> {
    if options.transport.is_none() {
        return Err("no transport configured: enable the SDK crate's reqwest feature or set the canonical transport slot".to_string());
    }
    Ok(())
}

/// One attempt: the canonical transport when set, otherwise the native
/// `reqwest` stack (a fresh default client when none was configured).
pub async fn http_send(
    options: &ClientOptions,
    request: HttpRequest,
) -> Result<HttpResponse, HttpError> {
    if let Some(transport) = &options.transport {
        return transport(request).await;
    }
    native_send(options, request).await
}
#[cfg(feature = "reqwest")]
async fn native_send(
    options: &ClientOptions,
    request: HttpRequest,
) -> Result<HttpResponse, HttpError> {
    let client = options.client.clone().unwrap_or_default();
    let mut builder = client.request(request.method.parse::<reqwest::Method>()?, &request.url);
    for (name, value) in &request.headers {
        builder = builder.header(name.as_str(), value.as_str());
    }
    if let Some(body) = request.body {
        builder = builder.body(body);
    }
    let response = builder.send().await?;
    let status = response.status().as_u16();
    let headers: std::collections::HashMap<String, String> = response
        .headers()
        .iter()
        .map(|(k, v)| {
            (
                k.as_str().to_lowercase(),
                v.to_str().unwrap_or_default().to_string(),
            )
        })
        .collect();
    let body = response.text().await?;
    Ok(HttpResponse {
        status,
        headers,
        body,
    })
}
#[cfg(not(feature = "reqwest"))]
async fn native_send(
    _options: &ClientOptions,
    _request: HttpRequest,
) -> Result<HttpResponse, HttpError> {
    Err("no transport configured: enable the SDK crate's reqwest feature or set the canonical transport slot".into())
}

/// Bounds one attempt: the deadline covers the transport call only
/// (`tokio::time::timeout` drops the attempt's future, which is Rust's
/// native cancellation), so a transport that never answers still
/// times out. A non-positive deadline means no deadline.
pub async fn http_send_with_timeout(
    options: &ClientOptions,
    request: HttpRequest,
    timeout_ms: f64,
) -> Result<HttpResponse, HttpError> {
    if timeout_ms <= 0.0 {
        return http_send(options, request).await;
    }
    let deadline = std::time::Duration::from_secs_f64(timeout_ms / 1000.0);
    match tokio::time::timeout(deadline, http_send(options, request)).await {
        Ok(result) => result,
        Err(_elapsed) => Err(format!("attempt timed out after {timeout_ms}ms").into()),
    }
}

/// The sleep behind the retry loop's backoff, held as a swappable
/// `pub(crate)` field on the generated client rather than called
/// directly: the parity harness (a `#[cfg(test)]` module of the same
/// crate) pins it to record delays deterministically. Milliseconds,
/// matching the backoff math every target shares.
pub type SleepFn = std::sync::Arc<dyn Fn(f64) -> BoxFuture<'static, ()> + Send + Sync>;
