// Code generated by tono. DO NOT EDIT.

use crate::payments_serde::{base64_bytes, i64_string, u64_string};

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct LocalDate(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Charge {
    pub id: String,
    #[serde(with = "i64_string")]
    pub amount: i64,
    #[serde(with = "u64_string")]
    pub fee: u64,
    #[serde(with = "base64_bytes")]
    pub receipt: Vec<u8>,
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    pub tags: Vec<String>,
    pub metadata: std::collections::HashMap<String, String>,
    pub created: Timestamp,
    pub status: Status,
    pub method: PaymentMethod,
}

#[derive(Clone, Debug)]
pub enum Status {
    Active,
    Settled,
    Refunded,
    Unknown(String),
}

#[derive(Clone, Debug)]
pub enum HTTPCode {
    Ok,
    NotFound,
    Error,
    Unknown(i64),
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Card {
    pub last4: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BankAccount {
    pub iban: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind")]
pub enum PaymentMethod {
    #[serde(rename = "card")]
    Card(Card),
    #[serde(rename = "bank")]
    Bank(BankAccount),
}
