// Code generated by tono. DO NOT EDIT.

use crate::payments::*;

macro_rules! open_enum {
    ($name:ident : $wire:ty { $($variant:ident => $repr:expr),* $(,)? }) => {
        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                match self {
                    $($name::$variant => serde::Serialize::serialize(&$repr, s),)*
                    $name::Unknown(v) => serde::Serialize::serialize(v, s),
                }
            }
        }
        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let v = <$wire as serde::Deserialize>::deserialize(d)?;
                $(if v == $repr {
                    return Ok($name::$variant);
                })*
                Ok($name::Unknown(v))
            }
        }
    };
}

pub mod i64_string {
    pub fn serialize<S: serde::Serializer>(v: &i64, s: S) -> Result<S::Ok, S::Error> {
        if s.is_human_readable() {
            s.serialize_str(&v.to_string())
        } else {
            serde::Serialize::serialize(v, s)
        }
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<i64, D::Error> {
        if d.is_human_readable() {
            let s = <String as serde::Deserialize>::deserialize(d)?;
            s.parse().map_err(serde::de::Error::custom)
        } else {
            <i64 as serde::Deserialize>::deserialize(d)
        }
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(v: &Option<i64>, s: S) -> Result<S::Ok, S::Error> {
            match v {
                Some(n) => super::serialize(n, s),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<i64>, D::Error> {
            if d.is_human_readable() {
                let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
                match o {
                    Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                    None => Ok(None),
                }
            } else {
                <Option<i64> as serde::Deserialize>::deserialize(d)
            }
        }
    }
}

pub mod u64_string {
    pub fn serialize<S: serde::Serializer>(v: &u64, s: S) -> Result<S::Ok, S::Error> {
        if s.is_human_readable() {
            s.serialize_str(&v.to_string())
        } else {
            serde::Serialize::serialize(v, s)
        }
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<u64, D::Error> {
        if d.is_human_readable() {
            let s = <String as serde::Deserialize>::deserialize(d)?;
            s.parse().map_err(serde::de::Error::custom)
        } else {
            <u64 as serde::Deserialize>::deserialize(d)
        }
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(v: &Option<u64>, s: S) -> Result<S::Ok, S::Error> {
            match v {
                Some(n) => super::serialize(n, s),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<u64>, D::Error> {
            if d.is_human_readable() {
                let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
                match o {
                    Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                    None => Ok(None),
                }
            } else {
                <Option<u64> as serde::Deserialize>::deserialize(d)
            }
        }
    }
}

pub mod base64_bytes {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    pub fn encode(bytes: &[u8]) -> String {
        let mut out = String::new();
        for chunk in bytes.chunks(3) {
            let b = [
                chunk[0],
                *chunk.get(1).unwrap_or(&0),
                *chunk.get(2).unwrap_or(&0),
            ];
            let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
            out.push(ALPHABET[((n >> 18) & 63) as usize] as char);
            out.push(ALPHABET[((n >> 12) & 63) as usize] as char);
            out.push(if chunk.len() > 1 {
                ALPHABET[((n >> 6) & 63) as usize] as char
            } else {
                '='
            });
            out.push(if chunk.len() > 2 {
                ALPHABET[(n & 63) as usize] as char
            } else {
                '='
            });
        }
        out
    }

    pub fn decode(s: &str) -> Result<Vec<u8>, String> {
        fn val(c: u8) -> Result<u32, String> {
            match c {
                b'A'..=b'Z' => Ok(u32::from(c - b'A')),
                b'a'..=b'z' => Ok(u32::from(c - b'a' + 26)),
                b'0'..=b'9' => Ok(u32::from(c - b'0' + 52)),
                b'+' => Ok(62),
                b'/' => Ok(63),
                _ => Err("invalid base64".to_string()),
            }
        }
        let bytes: Vec<u8> = s.bytes().filter(|&c| c != b'=').collect();
        let mut out = Vec::new();
        for chunk in bytes.chunks(4) {
            let mut n = 0u32;
            for (i, &c) in chunk.iter().enumerate() {
                n |= val(c)? << (18 - 6 * i);
            }
            out.push((n >> 16) as u8);
            if chunk.len() > 2 {
                out.push((n >> 8) as u8);
            }
            if chunk.len() > 3 {
                out.push(n as u8);
            }
        }
        Ok(out)
    }

    pub fn serialize<S: serde::Serializer>(v: &[u8], s: S) -> Result<S::Ok, S::Error> {
        if s.is_human_readable() {
            s.serialize_str(&encode(v))
        } else {
            s.serialize_bytes(v)
        }
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        if d.is_human_readable() {
            let s = <String as serde::Deserialize>::deserialize(d)?;
            decode(&s).map_err(serde::de::Error::custom)
        } else {
            <Vec<u8> as serde::Deserialize>::deserialize(d)
        }
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(
            v: &Option<Vec<u8>>,
            s: S,
        ) -> Result<S::Ok, S::Error> {
            match v {
                Some(b) => super::serialize(b, s),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<Vec<u8>>, D::Error> {
            if d.is_human_readable() {
                let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
                match o {
                    Some(s) => super::decode(&s)
                        .map(Some)
                        .map_err(serde::de::Error::custom),
                    None => Ok(None),
                }
            } else {
                <Option<Vec<u8>> as serde::Deserialize>::deserialize(d)
            }
        }
    }
}

open_enum!(Status: String {
    Active => "active",
    Settled => "settled",
    Refunded => "refunded",
});

open_enum!(HTTPCode: i64 {
    Ok => 200i64,
    NotFound => 404i64,
    Error => 500i64,
});

pub fn decode_create_charge_error(status: u16, body: &str) -> TonoError {
    let value: serde_json::Value = match serde_json::from_str(body) {
        Ok(value) => value,
        Err(_) => {
            return TonoError::Api(APIFailure::Undeclared(APIError {
                status,
                body: body.to_string(),
            }))
        }
    };
    let code = value.get("code").and_then(|v| v.as_str());
    if status == 402 && code == Some("card_declined") {
        if let Ok(data) = serde_json::from_value::<CardDeclined>(value.clone()) {
            return TonoError::Api(APIFailure::CardDeclined(data));
        }
    }
    if status == 404 {
        if let Ok(data) = serde_json::from_value::<NotFound>(value.clone()) {
            return TonoError::Api(APIFailure::NotFound(data));
        }
    }
    TonoError::Api(APIFailure::Undeclared(APIError {
        status,
        body: body.to_string(),
    }))
}
