// Code generated by tono. DO NOT EDIT.

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct LocalDate(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Uuid(pub String);

pub mod i64_string {
    pub fn serialize<S: serde::Serializer>(v: &i64, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&v.to_string())
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<i64, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        s.parse().map_err(serde::de::Error::custom)
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(v: &Option<i64>, s: S) -> Result<S::Ok, S::Error> {
            match v {
                Some(n) => s.serialize_str(&n.to_string()),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<i64>, D::Error> {
            let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
            match o {
                Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                None => Ok(None),
            }
        }
    }
}

pub mod u64_string {
    pub fn serialize<S: serde::Serializer>(v: &u64, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&v.to_string())
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<u64, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        s.parse().map_err(serde::de::Error::custom)
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(v: &Option<u64>, s: S) -> Result<S::Ok, S::Error> {
            match v {
                Some(n) => s.serialize_str(&n.to_string()),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<u64>, D::Error> {
            let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
            match o {
                Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                None => Ok(None),
            }
        }
    }
}

pub mod base64_bytes {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

    pub fn encode(bytes: &[u8]) -> String {
        let mut out = String::new();
        for chunk in bytes.chunks(3) {
            let b = [
                chunk[0],
                *chunk.get(1).unwrap_or(&0),
                *chunk.get(2).unwrap_or(&0),
            ];
            let n = (u32::from(b[0]) << 16) | (u32::from(b[1]) << 8) | u32::from(b[2]);
            out.push(ALPHABET[((n >> 18) & 63) as usize] as char);
            out.push(ALPHABET[((n >> 12) & 63) as usize] as char);
            out.push(if chunk.len() > 1 {
                ALPHABET[((n >> 6) & 63) as usize] as char
            } else {
                '='
            });
            out.push(if chunk.len() > 2 {
                ALPHABET[(n & 63) as usize] as char
            } else {
                '='
            });
        }
        out
    }

    pub fn decode(s: &str) -> Result<Vec<u8>, String> {
        fn val(c: u8) -> Result<u32, String> {
            match c {
                b'A'..=b'Z' => Ok(u32::from(c - b'A')),
                b'a'..=b'z' => Ok(u32::from(c - b'a' + 26)),
                b'0'..=b'9' => Ok(u32::from(c - b'0' + 52)),
                b'+' => Ok(62),
                b'/' => Ok(63),
                _ => Err("invalid base64".to_string()),
            }
        }
        let bytes: Vec<u8> = s.bytes().filter(|&c| c != b'=').collect();
        let mut out = Vec::new();
        for chunk in bytes.chunks(4) {
            let mut n = 0u32;
            for (i, &c) in chunk.iter().enumerate() {
                n |= val(c)? << (18 - 6 * i);
            }
            out.push((n >> 16) as u8);
            if chunk.len() > 2 {
                out.push((n >> 8) as u8);
            }
            if chunk.len() > 3 {
                out.push(n as u8);
            }
        }
        Ok(out)
    }

    pub fn serialize<S: serde::Serializer>(v: &[u8], s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(&encode(v))
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<Vec<u8>, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        decode(&s).map_err(serde::de::Error::custom)
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(
            v: &Option<Vec<u8>>,
            s: S,
        ) -> Result<S::Ok, S::Error> {
            match v {
                Some(b) => s.serialize_str(&super::encode(b)),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<Vec<u8>>, D::Error> {
            let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
            match o {
                Some(s) => super::decode(&s)
                    .map(Some)
                    .map_err(serde::de::Error::custom),
                None => Ok(None),
            }
        }
    }
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Charge {
    pub id: Uuid,
    #[serde(with = "i64_string")]
    pub amount: i64,
    #[serde(with = "u64_string")]
    pub fee: u64,
    #[serde(with = "base64_bytes")]
    pub receipt: Vec<u8>,
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    pub tags: Vec<String>,
    pub metadata: std::collections::HashMap<String, String>,
    pub created: Timestamp,
    pub status: Status,
    pub method: PaymentMethod,
}

#[derive(Clone, Debug)]
pub enum Status {
    Active,
    Settled,
    Refunded,
    Unknown(String),
}

impl Status {
    fn as_wire(&self) -> &str {
        match self {
            Status::Active => "active",
            Status::Settled => "settled",
            Status::Refunded => "refunded",
            Status::Unknown(s) => s.as_str(),
        }
    }
}

impl serde::Serialize for Status {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for Status {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(match s.as_str() {
            "active" => Status::Active,
            "settled" => Status::Settled,
            "refunded" => Status::Refunded,
            _ => Status::Unknown(s),
        })
    }
}

#[derive(Clone, Debug)]
pub enum HTTPCode {
    Ok,
    NotFound,
    Error,
    Unknown(String),
}

impl HTTPCode {
    fn as_wire(&self) -> &str {
        match self {
            HTTPCode::Ok => "ok",
            HTTPCode::NotFound => "not_found",
            HTTPCode::Error => "error",
            HTTPCode::Unknown(s) => s.as_str(),
        }
    }
}

impl serde::Serialize for HTTPCode {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.as_wire())
    }
}

impl<'de> serde::Deserialize<'de> for HTTPCode {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        let s = <String as serde::Deserialize>::deserialize(d)?;
        Ok(match s.as_str() {
            "ok" => HTTPCode::Ok,
            "not_found" => HTTPCode::NotFound,
            "error" => HTTPCode::Error,
            _ => HTTPCode::Unknown(s),
        })
    }
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Card {
    pub last4: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct BankAccount {
    pub iban: String,
}

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(tag = "kind")]
pub enum PaymentMethod {
    #[serde(rename = "card")]
    Card(Card),
    #[serde(rename = "bank")]
    Bank(BankAccount),
}
