// Code generated by tono. DO NOT EDIT.

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

impl std::fmt::Display for Timestamp {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

#[derive(Clone, Debug, PartialEq, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

impl std::fmt::Display for Duration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
