//! Driving the whole engine end to end: a decoded IR model in, the SDK source
//! files for the requested targets out, all in memory.
//!
//! [`generate`] is the payload behind the `tono gen` CLI. It produces *rough*
//! source — syntactically valid but unformatted — so it stays pure and
//! deterministic (no language formatter need be installed to test it). Running
//! each language's real formatter and writing to disk is the CLI's job.

use std::path::PathBuf;

use crate::codegen::render::render_file;
use crate::codegen::targets::{go, rust, typescript};
use crate::codegen::tree::ModuleFile;
use crate::codegen::Formatter;
use crate::ir::{Model, Module};

/// The banner every generated file carries. The exact `Code generated … DO NOT
/// EDIT.` wording is the convention Go tooling recognizes, and reads the same in
/// Rust and TypeScript.
const BANNER: &str = "// Code generated by tono. DO NOT EDIT.\n\n";

/// A language the generator can emit.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TargetKind {
    Rust,
    Go,
    TypeScript,
}

impl TargetKind {
    /// Parse a target name as accepted on the command line (`ts` aliases
    /// `typescript`).
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "rust" => Some(Self::Rust),
            "go" => Some(Self::Go),
            "typescript" | "ts" => Some(Self::TypeScript),
            _ => None,
        }
    }

    /// The conventional output subdirectory for this target.
    pub fn dir(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Go => "go",
            Self::TypeScript => "typescript",
        }
    }

    /// The source-file extension for this target.
    pub fn extension(self) -> &'static str {
        match self {
            Self::Rust => "rs",
            Self::Go => "go",
            Self::TypeScript => "ts",
        }
    }
}

/// A generated source file: which target produced it (so a caller knows which
/// formatter to run), its path relative to the output root, and its text.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedFile {
    pub target: TargetKind,
    pub path: PathBuf,
    pub text: String,
}

/// Emit every output file a module produces for a target. Most targets emit one
/// file; Go emits its types and its serialization separately, so this returns one
/// or more [`ModuleFile`]s.
fn emit_module_files(module: &Module, target: TargetKind) -> Vec<ModuleFile> {
    match target {
        TargetKind::Rust => rust::emit::emit_module(module, &rust::types::rust_casing()),
        TargetKind::Go => go::emit::emit_module(module, &go::types::go_casing()),
        TargetKind::TypeScript => {
            typescript::emit::emit_module(module, &typescript::types::ts_casing())
        }
    }
}

/// Render one of a module's output files into rough source text: the banner, then
/// the rendered declarations (with the package clause prepended for Go). The `cat`
/// passthrough keeps the engine's layout without depending on a real formatter.
fn render_module(module_file: &ModuleFile, module: &Module, target: TargetKind) -> String {
    let passthrough = Formatter::new("cat", vec![]);
    let rendered = match target {
        TargetKind::Rust => render_file(&module_file.file, &rust::RustRules, &passthrough).text,
        TargetKind::Go => {
            let rough = render_file(&module_file.file, &go::GoRules, &passthrough).text;
            format!("{}{}", go::emit::package_clause(&module.name), rough)
        }
        TargetKind::TypeScript => {
            render_file(&module_file.file, &typescript::TsRules, &passthrough).text
        }
    };
    format!("{BANNER}{rendered}")
}

/// Parse a comma-separated target list (e.g. `"rust,go,ts"`) into kinds,
/// rejecting any unknown name.
pub fn parse_targets(csv: &str) -> Result<Vec<TargetKind>, String> {
    csv.split(',')
        .map(|name| {
            let name = name.trim();
            TargetKind::parse(name).ok_or_else(|| format!("unknown target: {name}"))
        })
        .collect()
}

/// Generate the SDK source for every `(target, module)` pair. Each file lands at
/// `<target-dir>/<module-name>.<ext>`; the text is rough (unformatted) so callers
/// run the real formatter when they write it out.
pub fn generate(model: &Model, targets: &[TargetKind]) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for &target in targets {
        for module in &model.modules {
            for module_file in emit_module_files(module, target) {
                let path = PathBuf::from(target.dir()).join(format!(
                    "{}{}.{}",
                    module.name,
                    module_file.suffix,
                    target.extension()
                ));
                files.push(GeneratedFile {
                    target,
                    path,
                    text: render_module(&module_file, module, target),
                });
            }
        }
    }
    files
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::{member, structure, union_shape};
    use crate::ir::{Prim, Tref};

    /// A model whose Go module carries a union, so Go splits into two files while
    /// Rust and TypeScript stay single-file.
    fn union_model() -> Model {
        Model {
            tono_ir_version: 2,
            modules: vec![Module {
                name: "payments".into(),
                shapes: vec![
                    structure(
                        "payments#Account",
                        vec![member(
                            "method",
                            Tref::Ref {
                                id: "payments#Method".into(),
                                args: vec![],
                            },
                            true,
                        )],
                    ),
                    union_shape(
                        "payments#Method",
                        "type",
                        vec![member(
                            "card",
                            Tref::Ref {
                                id: "payments#Card".into(),
                                args: vec![],
                            },
                            true,
                        )],
                    ),
                    structure(
                        "payments#Card",
                        vec![member("last4", Tref::Prim(Prim::String), true)],
                    ),
                ],
                operations: vec![],
            }],
        }
    }

    fn demo_model() -> Model {
        Model {
            tono_ir_version: 2,
            modules: vec![Module {
                name: "payments".into(),
                shapes: vec![structure(
                    "payments#Charge",
                    vec![member("amount", Tref::Prim(Prim::I64), true)],
                )],
                operations: vec![],
            }],
        }
    }

    #[test]
    fn target_kind_parses_names_and_aliases() {
        assert_eq!(TargetKind::parse("rust"), Some(TargetKind::Rust));
        assert_eq!(TargetKind::parse("go"), Some(TargetKind::Go));
        assert_eq!(
            TargetKind::parse("typescript"),
            Some(TargetKind::TypeScript)
        );
        assert_eq!(TargetKind::parse("ts"), Some(TargetKind::TypeScript));
        assert_eq!(TargetKind::parse("java"), None);
    }

    #[test]
    fn target_kind_dirs_and_extensions() {
        for (target, dir, ext) in [
            (TargetKind::Rust, "rust", "rs"),
            (TargetKind::Go, "go", "go"),
            (TargetKind::TypeScript, "typescript", "ts"),
        ] {
            assert_eq!(target.dir(), dir);
            assert_eq!(target.extension(), ext);
        }
    }

    #[test]
    fn generate_emits_one_file_per_target_and_module() {
        let model = demo_model();
        let files = generate(
            &model,
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
        );
        let paths: Vec<String> = files
            .iter()
            .map(|f| f.path.to_string_lossy().into_owned())
            .collect();
        assert_eq!(
            paths,
            vec![
                format!("rust{}payments.rs", std::path::MAIN_SEPARATOR),
                format!("go{}payments.go", std::path::MAIN_SEPARATOR),
                format!("typescript{}payments.ts", std::path::MAIN_SEPARATOR),
            ]
        );
        // Every file carries the banner; each target spells the struct its own way
        // and Go carries its package clause.
        assert!(files.iter().all(|f| f.text.starts_with(BANNER)));
        assert!(files[0].text.contains("pub struct Charge"));
        assert!(files[1].text.contains("package payments"));
        assert!(files[1].text.contains("type Charge struct"));
        assert!(files[2].text.contains("export interface Charge"));
    }

    #[test]
    fn go_splits_a_union_module_into_types_and_serde_while_others_stay_single() {
        let files = generate(
            &union_model(),
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
        );
        let paths: Vec<String> = files
            .iter()
            .map(|f| f.path.to_string_lossy().into_owned())
            .collect();
        let sep = std::path::MAIN_SEPARATOR;
        // Go gets a types file and a _serde file; Rust and TypeScript keep one each.
        assert_eq!(
            paths,
            vec![
                format!("rust{sep}payments.rs"),
                format!("go{sep}payments.go"),
                format!("go{sep}payments_serde.go"),
                format!("typescript{sep}payments.ts"),
            ]
        );
        let go_types = &files[1];
        let go_serde = &files[2];
        // Every file keeps its banner and package clause; the split puts the interface
        // in the types file and the (de)serialization in the serde file.
        assert!(go_types.text.starts_with(BANNER));
        assert!(go_types.text.contains("package payments"));
        assert!(go_types
            .text
            .contains("type Method interface{ isMethod() }"));
        assert!(!go_types.text.contains("import "));
        assert!(!go_types.text.contains("MarshalJSON"));

        assert!(go_serde.text.starts_with(BANNER));
        assert!(go_serde.text.contains("package payments"));
        assert!(go_serde.text.contains("func marshalVariant("));
        assert!(go_serde
            .text
            .contains("func unmarshalMethod(b []byte) (Method, error) {"));
        assert!(go_serde
            .text
            .contains("func (a *Account) UnmarshalJSON(b []byte) error {"));
        assert!(go_serde.text.contains("import \"encoding/json\""));
        assert!(go_serde.text.contains("import \"fmt\""));
    }

    #[test]
    fn generate_with_no_targets_is_empty() {
        assert!(generate(&demo_model(), &[]).is_empty());
    }

    #[test]
    fn parse_targets_accepts_a_list_and_rejects_unknowns() {
        assert_eq!(
            parse_targets("rust, go ,ts").unwrap(),
            vec![TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript]
        );
        assert!(parse_targets("rust,java").is_err());
    }
}
