//! Driving the whole engine end to end: a decoded IR model in, the SDK source
//! files for the requested targets out, all in memory.
//!
//! [`generate`] is the payload behind the `tono gen` CLI. It produces *rough*
//! source — syntactically valid but unformatted — so it stays pure and
//! deterministic (no language formatter need be installed to test it). Running
//! each language's real formatter and writing to disk is the CLI's job.

use std::path::PathBuf;

use crate::codegen::casing::CasingConfig;
use crate::codegen::layout::{output_path, package_name, rust_mod_tree};
use crate::codegen::modules::{self, CodegenConfig};
use crate::codegen::render::render_file_with_companion;
use crate::codegen::targets::{go, rust, typescript};
use crate::codegen::tree::ModuleFile;
use crate::codegen::Formatter;
use crate::ir::{Model, Module};

/// The banner every generated file carries. The exact `Code generated … DO NOT
/// EDIT.` wording is the convention Go tooling recognizes, and reads the same in
/// Rust and TypeScript.
pub(crate) const BANNER: &str = "// Code generated by tono. DO NOT EDIT.\n\n";

/// A language the generator can emit.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum TargetKind {
    Rust,
    Go,
    TypeScript,
}

impl TargetKind {
    /// Parse a target name as accepted on the command line (`ts` aliases
    /// `typescript`).
    pub fn parse(name: &str) -> Option<Self> {
        match name {
            "rust" => Some(Self::Rust),
            "go" => Some(Self::Go),
            "typescript" | "ts" => Some(Self::TypeScript),
            _ => None,
        }
    }

    /// The conventional output subdirectory for this target.
    pub fn dir(self) -> &'static str {
        match self {
            Self::Rust => "rust",
            Self::Go => "go",
            Self::TypeScript => "typescript",
        }
    }

    /// The source-file extension for this target.
    pub fn extension(self) -> &'static str {
        match self {
            Self::Rust => "rs",
            Self::Go => "go",
            Self::TypeScript => "ts",
        }
    }
}

/// A generated source file: which target produced it (so a caller knows which
/// formatter to run), its path relative to the output root, and its text.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedFile {
    pub target: TargetKind,
    pub path: PathBuf,
    pub text: String,
}

/// Emit every output file a module produces for a target. Most targets emit one
/// file; Go emits its types and its serialization separately, so this returns one
/// or more [`ModuleFile`]s.
fn emit_module_files(
    module: &Module,
    target: TargetKind,
    casing: &CasingConfig,
    union_ids: &std::collections::HashSet<String>,
) -> Vec<ModuleFile> {
    match target {
        TargetKind::Rust => rust::emit::emit_module(module, casing),
        TargetKind::Go => go::emit::emit_module(module, casing, union_ids),
        TargetKind::TypeScript => typescript::emit::emit_module(module, casing),
    }
}

/// The idiomatic casing a target starts from, before any manifest override. A
/// config-driven caller layers `[target.<lang>.casing]` overrides on top with
/// [`CasingConfig::with`]; [`generate`] uses this base for every target.
pub fn casing_for(target: TargetKind) -> CasingConfig {
    match target {
        TargetKind::Rust => rust::types::rust_casing(),
        TargetKind::Go => go::types::go_casing(),
        TargetKind::TypeScript => typescript::types::ts_casing(),
    }
}

/// Render one of a module's output files into rough source text: the banner, then
/// the rendered declarations (with the package clause prepended for Go). The `cat`
/// passthrough keeps the engine's layout without depending on a real formatter.
fn render_module(
    module_file: &ModuleFile,
    module: &Module,
    target: TargetKind,
    config: &CodegenConfig,
    internal_modules: &std::collections::BTreeSet<String>,
) -> String {
    let passthrough = Formatter::new("cat", vec![]);
    let companion = module_file.imports_companion.as_deref();
    let rendered = match target {
        TargetKind::Rust => {
            render_file_with_companion(&module_file.file, companion, &rust::RustRules, &passthrough)
                .text
        }
        TargetKind::Go => {
            let go_rules = go::GoRules {
                go_module: config.go_module.clone(),
                internal_modules: internal_modules.clone(),
                current_module: module.name.clone(),
            };
            let rough =
                render_file_with_companion(&module_file.file, companion, &go_rules, &passthrough)
                    .text;
            // The Go package is named for the module's last segment; a dotted
            // module nests in a directory of that name (see [`output_path`]).
            format!(
                "{}{}",
                go::emit::package_clause(package_name(&module.name)),
                rough
            )
        }
        TargetKind::TypeScript => {
            render_file_with_companion(
                &module_file.file,
                companion,
                &typescript::TsRules,
                &passthrough,
            )
            .text
        }
    };
    format!("{BANNER}{rendered}")
}

/// Parse a comma-separated target list (e.g. `"rust,go,ts"`) into kinds,
/// rejecting any unknown name.
pub fn parse_targets(csv: &str) -> Result<Vec<TargetKind>, String> {
    csv.split(',')
        .map(|name| {
            let name = name.trim();
            TargetKind::parse(name).ok_or_else(|| format!("unknown target: {name}"))
        })
        .collect()
}

/// Reject a Go layout that would emit source Go cannot compile, so the failure is
/// a clear error rather than silently-broken output. Go has no relative imports,
/// so a multi-module SDK's cross-package imports need the module path
/// (`--go-module`); and a package is named for its module's last segment, so two
/// modules sharing that segment would render colliding `pkg.` selectors. Config is
/// applied first, so `--flatten` (which joins the whole path into one segment)
/// clears both conditions. A no-op when Go is not a requested target.
pub fn check_go_layout(
    model: &Model,
    targets: &[TargetKind],
    config: &CodegenConfig,
) -> Result<(), String> {
    if !targets.contains(&TargetKind::Go) {
        return Ok(());
    }
    let model = modules::apply(config, model);
    let names: Vec<&str> = model.modules.iter().map(|m| m.name.as_str()).collect();
    if names.len() > 1 && config.go_module.is_none() {
        return Err(
            "Go multi-module output needs --go-module <path>: Go has no relative \
             imports, so the cross-package imports need the SDK's module path"
                .into(),
        );
    }
    let mut by_pkg: std::collections::BTreeMap<&str, Vec<&str>> = std::collections::BTreeMap::new();
    for name in &names {
        by_pkg
            .entry(name.rsplit('.').next().unwrap_or(name))
            .or_default()
            .push(name);
    }
    if let Some((pkg, mods)) = by_pkg.iter().find(|(_, v)| v.len() > 1) {
        return Err(format!(
            "Go package name collision: modules {} both map to package '{pkg}'; \
             rename a module so its last segment is unique, or --flatten",
            mods.join(" and ")
        ));
    }
    Ok(())
}

/// The model and the cross-module indices every generation pass needs: the
/// module remap/flatten hooks applied once up front (so render rules and output
/// paths see only effective names), the SDK's own module names (so Go tells an
/// internal cross-package import from a standard-library one), and every union's
/// id (so Go can give a struct field a container `UnmarshalJSON` even when its
/// union type is in another module).
fn prepare(
    model: &Model,
    config: &CodegenConfig,
) -> (
    Model,
    std::collections::HashSet<String>,
    std::collections::BTreeSet<String>,
) {
    let model = modules::apply(config, model);
    let internal_modules: std::collections::BTreeSet<String> =
        model.modules.iter().map(|m| m.name.clone()).collect();
    let union_ids: std::collections::HashSet<String> = model
        .modules
        .iter()
        .flat_map(|m| &m.shapes)
        .filter(|s| matches!(s.kind, crate::ir::ShapeKind::Union { .. }))
        .map(|s| s.id.clone())
        .collect();
    (model, union_ids, internal_modules)
}

/// Emit one target's files over an already-prepared model, with the given casing.
/// Excludes the Rust module tree, which is synthesized once over the final set.
fn emit_target(
    model: &Model,
    target: TargetKind,
    casing: &CasingConfig,
    config: &CodegenConfig,
    union_ids: &std::collections::HashSet<String>,
    internal_modules: &std::collections::BTreeSet<String>,
) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    for module in &model.modules {
        for module_file in emit_module_files(module, target, casing, union_ids) {
            let path = output_path(target, &module.name, module_file.suffix, target.extension());
            files.push(GeneratedFile {
                target,
                path,
                text: render_module(&module_file, module, target, config, internal_modules),
            });
        }
    }
    files
}

/// Generate the SDK source for every `(target, module)` pair, mapping each module
/// to its idiomatic sub-package (steered by `config`) with each target's idiomatic
/// casing. Each file's text is rough (unformatted) so callers run the real
/// formatter when they write it out. Fails if the bespoke gate
/// ([`extensions::validate_extensions`]) rejects the model. [`generate_target`] is
/// the per-target, casing-overridable variant the manifest path uses.
pub fn generate(
    model: &Model,
    targets: &[TargetKind],
    config: &CodegenConfig,
) -> Result<Vec<GeneratedFile>, String> {
    crate::codegen::extensions::validate_extensions(model)?;
    let (model, union_ids, internal_modules) = prepare(model, config);
    let mut files = Vec::new();
    for &target in targets {
        files.extend(emit_target(
            &model,
            target,
            &casing_for(target),
            config,
            &union_ids,
            &internal_modules,
        ));
    }
    // Rust needs a module tree so `use crate::a::b` resolves; a nested layout gets
    // a `mod.rs` per directory declaring its children.
    if targets.contains(&TargetKind::Rust) {
        files.extend(rust_mod_tree(&files));
    }
    Ok(files)
}

/// Generate the SDK source for a single target with an explicit casing (the
/// manifest's `[target.<lang>.casing]` overrides layered on the language default).
/// Paths carry the `<target-dir>/` prefix, like [`generate`], so a config-driven
/// caller strips it and rewrites each target under its own configured `out`.
/// Subject to the same bespoke gate as [`generate`].
pub fn generate_target(
    model: &Model,
    target: TargetKind,
    config: &CodegenConfig,
    casing: &CasingConfig,
) -> Result<Vec<GeneratedFile>, String> {
    crate::codegen::extensions::validate_extensions(model)?;
    let (model, union_ids, internal_modules) = prepare(model, config);
    let mut files = emit_target(
        &model,
        target,
        casing,
        config,
        &union_ids,
        &internal_modules,
    );
    if target == TargetKind::Rust {
        files.extend(rust_mod_tree(&files));
    }
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::codegen::test_support::{member, structure, union_shape};
    use crate::ir::{Prim, Shape, ShapeKind, Tref};

    /// A model whose Go module carries a union, so Go splits into two files while
    /// Rust and TypeScript stay single-file.
    fn union_model() -> Model {
        Model {
            tono_ir_version: 3,
            modules: vec![Module {
                name: "payments".into(),
                shapes: vec![
                    structure(
                        "payments#Account",
                        vec![member(
                            "method",
                            Tref::Ref {
                                id: "payments#Method".into(),
                                args: vec![],
                            },
                            true,
                        )],
                    ),
                    union_shape(
                        "payments#Method",
                        "type",
                        vec![member(
                            "card",
                            Tref::Ref {
                                id: "payments#Card".into(),
                                args: vec![],
                            },
                            true,
                        )],
                    ),
                    structure(
                        "payments#Card",
                        vec![member("last4", Tref::Prim(Prim::String), true)],
                    ),
                ],
                operations: vec![],
                extensions: vec![],
            }],
        }
    }

    fn demo_model() -> Model {
        Model {
            tono_ir_version: 3,
            modules: vec![Module {
                name: "payments".into(),
                shapes: vec![structure(
                    "payments#Charge",
                    vec![member("amount", Tref::Prim(Prim::I64), true)],
                )],
                operations: vec![],
                extensions: vec![],
            }],
        }
    }

    #[test]
    fn target_kind_parses_names_and_aliases() {
        assert_eq!(TargetKind::parse("rust"), Some(TargetKind::Rust));
        assert_eq!(TargetKind::parse("go"), Some(TargetKind::Go));
        assert_eq!(
            TargetKind::parse("typescript"),
            Some(TargetKind::TypeScript)
        );
        assert_eq!(TargetKind::parse("ts"), Some(TargetKind::TypeScript));
        assert_eq!(TargetKind::parse("java"), None);
    }

    #[test]
    fn target_kind_dirs_and_extensions() {
        for (target, dir, ext) in [
            (TargetKind::Rust, "rust", "rs"),
            (TargetKind::Go, "go", "go"),
            (TargetKind::TypeScript, "typescript", "ts"),
        ] {
            assert_eq!(target.dir(), dir);
            assert_eq!(target.extension(), ext);
        }
    }

    #[test]
    fn generate_splits_each_target_that_has_serialization_to_emit() {
        let model = demo_model();
        let files = generate(
            &model,
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
            &CodegenConfig::default(),
        )
        .unwrap();
        let paths: Vec<String> = files
            .iter()
            .map(|f| f.path.to_string_lossy().into_owned())
            .collect();
        let sep = std::path::MAIN_SEPARATOR;
        // The single i64 field gives Rust a helper module and TypeScript codecs, so
        // both split; Go's plain tagged struct needs no custom serde, so it stays one
        // file.
        assert_eq!(
            paths,
            vec![
                format!("rust{sep}payments.rs"),
                format!("rust{sep}payments_serde.rs"),
                format!("go{sep}payments.go"),
                format!("typescript{sep}payments.ts"),
                format!("typescript{sep}payments_serde.ts"),
            ]
        );
        // Every file carries the banner; each target spells the struct its own way
        // in its types file and Go carries its package clause.
        assert!(files.iter().all(|f| f.text.starts_with(BANNER)));
        assert!(files[0].text.contains("pub struct Charge"));
        assert!(files[1].text.contains("pub mod i64_string"));
        assert!(files[2].text.contains("package payments"));
        assert!(files[2].text.contains("type Charge struct"));
        assert!(files[3].text.contains("export interface Charge"));
        assert!(files[4].text.contains("export function encodeCharge"));
        assert!(files[4]
            .text
            .contains("import { Charge } from \"./payments\";"));
    }

    #[test]
    fn a_union_module_splits_go_and_typescript_but_rusts_derive_keeps_it_single() {
        let files = generate(
            &union_model(),
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
            &CodegenConfig::default(),
        )
        .unwrap();
        let paths: Vec<String> = files
            .iter()
            .map(|f| f.path.to_string_lossy().into_owned())
            .collect();
        let sep = std::path::MAIN_SEPARATOR;
        // Go needs hand-written union marshaling and TypeScript needs codecs, so both
        // split. Rust's tagged-union enum derives its serde on the type with no wide
        // integer, bytes, or open enum in the module, so there is nothing for a serde
        // file to hold and Rust stays single.
        assert_eq!(
            paths,
            vec![
                format!("rust{sep}payments.rs"),
                format!("go{sep}payments.go"),
                format!("go{sep}payments_serde.go"),
                format!("typescript{sep}payments.ts"),
                format!("typescript{sep}payments_serde.ts"),
            ]
        );
        let go_types = &files[1];
        let go_serde = &files[2];
        // Every file keeps its banner and package clause; the split puts the interface
        // in the types file and the (de)serialization in the serde file.
        assert!(go_types.text.starts_with(BANNER));
        assert!(go_types.text.contains("package payments"));
        assert!(go_types
            .text
            .contains("type Method interface{ isMethod() }"));
        assert!(!go_types.text.contains("import "));
        assert!(!go_types.text.contains("MarshalJSON"));

        assert!(go_serde.text.starts_with(BANNER));
        assert!(go_serde.text.contains("package payments"));
        assert!(go_serde.text.contains("func marshalVariant("));
        assert!(go_serde
            .text
            .contains("func UnmarshalMethod(b []byte) (Method, error) {"));
        assert!(go_serde
            .text
            .contains("func (a *Account) UnmarshalJSON(b []byte) error {"));
        assert!(go_serde.text.contains("import \"encoding/json\""));
        assert!(go_serde.text.contains("import \"fmt\""));
    }

    /// A model with one async operation declaring one error, so every target
    /// emits the error surface, the client, and the discriminator.
    fn ops_model() -> Model {
        let mut not_found = structure(
            "payments#not_found",
            vec![member("message", Tref::Prim(Prim::String), true)],
        );
        not_found.traits = vec![crate::ir::Trait {
            id: "core#status".into(),
            value: serde_json::json!([404]),
        }];
        let mut model = demo_model();
        model.modules[0].shapes.push(not_found);
        model.modules[0].operations = vec![Shape {
            id: "payments#get_charge".into(),
            kind: ShapeKind::Operation {
                input: None,
                output: Some(Tref::Ref {
                    id: "payments#Charge".into(),
                    args: vec![],
                }),
                errors: vec![Tref::Ref {
                    id: "payments#not_found".into(),
                    args: vec![],
                }],
            },
            traits: vec![crate::ir::Trait {
                id: "core#http".into(),
                value: serde_json::json!({"method": "GET", "path": "/charges/{id}"}),
            }],
        }];
        model
    }

    #[test]
    fn a_module_with_operations_generates_the_error_surface_in_every_target() {
        let files = generate(
            &ops_model(),
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
            &CodegenConfig::default(),
        )
        .unwrap();
        let text_of = |path: &str| {
            files
                .iter()
                .find(|f| f.path.to_string_lossy().replace('\\', "/") == path)
                .unwrap_or_else(|| panic!("missing {path}"))
                .text
                .clone()
        };

        // Rust: the enum root, the Api payload enum, the async client trait, and
        // the discriminator next to the serde helpers.
        let rust_types = text_of("rust/payments.rs");
        assert!(rust_types.contains("pub enum TonoError {"));
        assert!(rust_types.contains("Undeclared(APIError),"));
        assert!(rust_types.contains("async fn get_charge(&self) -> Result<Charge, TonoError>;"));
        let rust_serde = text_of("rust/payments_serde.rs");
        assert!(rust_serde
            .contains("pub fn decode_get_charge_error(status: u16, body: &str) -> TonoError {"));

        // Go: error values with no root, the blocking interface, and the
        // discriminator in the serde file.
        let go_types = text_of("go/payments.go");
        assert!(go_types.contains("type APIError struct {"));
        assert!(!go_types.contains("TonoError"));
        assert!(go_types.contains("GetCharge() (Charge, error)"));
        assert!(go_types.contains("func (e *NotFound) Retryable() bool { return false }"));
        let go_serde = text_of("go/payments_serde.go");
        assert!(go_serde.contains("func DecodeGetChargeError(status int, body []byte) error {"));

        // TypeScript: the class hierarchy, the Promise-returning client, and the
        // discriminator with the codecs.
        let ts_types = text_of("typescript/payments.ts");
        assert!(ts_types.contains("export abstract class TonoError extends Error {"));
        assert!(ts_types.contains("export class NotFoundError extends APIError {"));
        assert!(ts_types.contains("getCharge(): Promise<Charge>;"));
        let ts_serde = text_of("typescript/payments_serde.ts");
        assert!(ts_serde.contains(
            "export function decodeGetChargeError(status: number, body: string): TonoError {"
        ));
        assert!(ts_serde.contains(
            "import { APIError, Charge, NotFound, NotFoundError, TonoError } from \"./payments\";"
        ));
    }

    #[test]
    fn generate_with_no_targets_is_empty() {
        let files = generate(&demo_model(), &[], &CodegenConfig::default()).unwrap();
        assert!(files.is_empty());
    }

    #[test]
    fn parse_targets_accepts_a_list_and_rejects_unknowns() {
        assert_eq!(
            parse_targets("rust, go ,ts").unwrap(),
            vec![TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript]
        );
        assert!(parse_targets("rust,java").is_err());
    }

    // ── Sub-package mapping and config hooks ────────────────────────────

    /// A two-module project: `payments.common` defines a type, `payments.charge`
    /// references it across the module boundary, exercising the dotted-module ->
    /// sub-package mapping and the cross-package import.
    fn sub_package_model() -> Model {
        Model {
            tono_ir_version: 2,
            modules: vec![
                Module {
                    name: "payments.common".into(),
                    shapes: vec![structure(
                        "payments.common#Money",
                        vec![member("amount", Tref::Prim(Prim::I64), true)],
                    )],
                    operations: vec![],
                    extensions: vec![],
                },
                Module {
                    name: "payments.charge".into(),
                    shapes: vec![structure(
                        "payments.charge#Charge",
                        vec![member(
                            "total",
                            Tref::Ref {
                                id: "payments.common#Money".into(),
                                args: vec![],
                            },
                            true,
                        )],
                    )],
                    operations: vec![],
                    extensions: vec![],
                },
            ],
        }
    }

    fn paths_of(files: &[GeneratedFile]) -> Vec<String> {
        files
            .iter()
            .map(|f| {
                f.path
                    .to_string_lossy()
                    .replace(std::path::MAIN_SEPARATOR, "/")
            })
            .collect()
    }

    fn text_at<'a>(files: &'a [GeneratedFile], path: &str) -> &'a str {
        let sep = std::path::MAIN_SEPARATOR_STR;
        let want = path.replace('/', sep);
        &files
            .iter()
            .find(|f| f.path.to_string_lossy() == want)
            .unwrap_or_else(|| panic!("no file at {path}"))
            .text
    }

    #[test]
    fn dotted_modules_map_to_idiomatic_sub_packages() {
        let files = generate(
            &sub_package_model(),
            &[TargetKind::Rust, TargetKind::Go, TargetKind::TypeScript],
            &CodegenConfig::default(),
        )
        .unwrap();
        let paths = paths_of(&files);
        // Rust and TypeScript use the dotted path as a file path; Go nests the
        // file inside a package directory named for the last segment.
        assert!(paths.contains(&"rust/payments/common.rs".to_string()));
        assert!(paths.contains(&"rust/payments/charge.rs".to_string()));
        assert!(paths.contains(&"go/payments/common/common.go".to_string()));
        assert!(paths.contains(&"typescript/payments/common.ts".to_string()));
        assert!(paths.contains(&"typescript/payments/charge.ts".to_string()));

        // The cross-package reference imports through each language's idiomatic
        // module path: Rust an absolute crate path and TypeScript a path relative
        // to the importing file. The Go cross-package import needs the module path
        // and is covered by [`go_module_prefix_makes_cross_package_imports_absolute`];
        // emitting it without a module path is rejected by [`check_go_layout`].
        assert!(text_at(&files, "rust/payments/charge.rs")
            .contains("use crate::payments::common::Money;"));
        assert!(text_at(&files, "typescript/payments/charge.ts").contains("from \"./common\""));
        // The Go package is named for the last segment, not the dotted path.
        assert!(text_at(&files, "go/payments/common/common.go").contains("package common"));

        // Rust gets a module tree so the crate paths resolve.
        assert!(paths.contains(&"rust/payments/mod.rs".to_string()));
        let mod_rs = text_at(&files, "rust/payments/mod.rs");
        assert!(mod_rs.contains("pub mod common;"));
        assert!(mod_rs.contains("pub mod charge;"));
    }

    #[test]
    fn go_module_prefix_makes_cross_package_imports_absolute() {
        let config = CodegenConfig {
            go_module: Some("example.com/sdk".into()),
            ..CodegenConfig::default()
        };
        let files = generate(&sub_package_model(), &[TargetKind::Go], &config).unwrap();
        assert!(text_at(&files, "go/payments/charge/charge.go")
            .contains("import \"example.com/sdk/payments/common\""));
    }

    #[test]
    fn flatten_collapses_modules_into_flat_packages() {
        let config = CodegenConfig {
            flatten: true,
            remap: vec![],
            go_module: None,
        };
        let files = generate(&sub_package_model(), &[TargetKind::Rust], &config).unwrap();
        let paths = paths_of(&files);
        assert!(paths.contains(&"rust/payments_common.rs".to_string()));
        assert!(paths.contains(&"rust/payments_charge.rs".to_string()));
        assert!(text_at(&files, "rust/payments_charge.rs")
            .contains("use crate::payments_common::Money;"));
    }

    #[test]
    fn remap_rewrites_the_module_prefix_in_paths_and_imports() {
        let config = CodegenConfig {
            flatten: false,
            remap: vec![("payments".into(), "billing".into())],
            go_module: None,
        };
        let files = generate(&sub_package_model(), &[TargetKind::Rust], &config).unwrap();
        let paths = paths_of(&files);
        assert!(paths.contains(&"rust/billing/common.rs".to_string()));
        assert!(paths.contains(&"rust/billing/charge.rs".to_string()));
        assert!(text_at(&files, "rust/billing/charge.rs")
            .contains("use crate::billing::common::Money;"));
    }

    #[test]
    fn single_segment_modules_keep_the_flat_layout() {
        // The common single-module case is unchanged by the sub-package mapping.
        let files = generate(&demo_model(), &[TargetKind::Go], &CodegenConfig::default()).unwrap();
        let paths = paths_of(&files);
        assert!(paths.contains(&"go/payments.go".to_string()));
    }

    #[test]
    fn go_multi_module_without_a_module_path_is_rejected() {
        // Multi-module Go with no module path would emit unresolvable bare imports.
        let err = check_go_layout(
            &sub_package_model(),
            &[TargetKind::Go],
            &CodegenConfig::default(),
        )
        .unwrap_err();
        assert!(err.contains("--go-module"));
        // The module path makes the cross-package imports resolve.
        let config = CodegenConfig {
            go_module: Some("example.com/sdk".into()),
            ..CodegenConfig::default()
        };
        assert!(check_go_layout(&sub_package_model(), &[TargetKind::Go], &config).is_ok());
        // Rust and TypeScript have relative imports, so the same layout is fine.
        assert!(check_go_layout(
            &sub_package_model(),
            &[TargetKind::Rust, TargetKind::TypeScript],
            &CodegenConfig::default()
        )
        .is_ok());
    }

    #[test]
    fn go_modules_sharing_a_last_segment_are_rejected() {
        // `a.common` and `b.common` both map to package `common` and would collide.
        let model = Model {
            tono_ir_version: 2,
            modules: vec![
                Module {
                    name: "a.common".into(),
                    shapes: vec![structure(
                        "a.common#Money",
                        vec![member("amount", Tref::Prim(Prim::I64), true)],
                    )],
                    operations: vec![],
                    extensions: vec![],
                },
                Module {
                    name: "b.common".into(),
                    shapes: vec![structure(
                        "b.common#Rate",
                        vec![member("pct", Tref::Prim(Prim::I64), true)],
                    )],
                    operations: vec![],
                    extensions: vec![],
                },
            ],
        };
        let config = CodegenConfig {
            go_module: Some("example.com/sdk".into()),
            ..CodegenConfig::default()
        };
        let err = check_go_layout(&model, &[TargetKind::Go], &config).unwrap_err();
        assert!(err.contains("package name collision"));
        // Flatten joins the whole path into one segment, so the packages differ.
        let flat = CodegenConfig {
            flatten: true,
            go_module: Some("example.com/sdk".into()),
            ..CodegenConfig::default()
        };
        assert!(check_go_layout(&model, &[TargetKind::Go], &flat).is_ok());
    }
}
