// The round-trip driver. The `models` module is generated by the harness at run
// time; this driver asserts the hard wire cases hold: a 64-bit integer above
// 2^53 travels as a JSON string, bytes travel as base64, an internally-tagged
// union carries its discriminator, the open enum decodes an unknown tag
// leniently, and a decode/re-encode is canonical (Value-equal) round-trip.
#![allow(dead_code)]

mod models;
// The generated serde file is a sibling module of the crate: it holds the
// `#[serde(with)]` helper modules and the open enum's impls, and references the
// types via `use crate::models::*`.
mod models_serde;

use models::{Account, CardData, Method, Status};
use serde_json::{json, Value};

fn main() {
    let big: i64 = 9_007_199_254_740_993; // 2^53 + 1, not representable as an f64
    let account = Account {
        account_id: big,
        secret: vec![1, 2, 3, 254],
        tip: Some(500),
        status: Status::Active,
        method: Method::Card(CardData {
            last4: "4242".into(),
        }),
        counts: vec![(7, "a".into()), (3, "b".into())],
    };

    let wire: Value = serde_json::to_value(&account).expect("encode");
    assert!(
        wire["account_id"].is_string(),
        "i64 must encode as a JSON string, got {}",
        wire["account_id"]
    );
    assert_eq!(wire["account_id"], Value::String(big.to_string()));
    assert!(
        wire["secret"].is_string(),
        "bytes must encode as a base64 string"
    );
    assert_eq!(wire["method"]["type"], Value::String("card".into()));
    assert_eq!(wire["tip"], Value::String("500".into()));
    // An @entries map travels as an array of [key, value] pairs.
    assert_eq!(wire["counts"], json!([[7, "a"], [3, "b"]]));

    // Canonical round-trip: decode then re-encode must equal the first wire JSON.
    let back: Account = serde_json::from_value(wire.clone()).expect("decode");
    let again: Value = serde_json::to_value(&back).expect("re-encode");
    assert_eq!(wire, again, "round-trip changed the JSON");

    // An open enum decodes an unknown tag leniently and preserves it.
    let unknown_json = json!({
        "account_id": "1",
        "secret": "AAEC/g==",
        "status": "frozen",
        "method": { "type": "card", "last4": "0000" },
        "counts": []
    });
    let unknown: Account = serde_json::from_value(unknown_json).expect("decode unknown");
    assert!(
        matches!(unknown.status, Status::Unknown(ref s) if s == "frozen"),
        "an unknown enum value must pass through"
    );

    println!("ROUNDTRIP_OK");
}
