// The round-trip driver. The `models` module is generated by the harness at run
// time; this driver asserts the hard wire cases hold: a 64-bit integer above
// 2^53 travels as a JSON string, bytes travel as base64, an internally-tagged
// union carries its discriminator, the open enum decodes an unknown tag
// leniently, and a decode/re-encode is canonical (Value-equal) round-trip.
#![allow(dead_code)]

mod models;
// The generated serde file is a sibling module of the crate: it holds the
// `#[serde(with)]` helper modules and the open enum's impls, and references the
// types via `use crate::models::*`.
mod models_serde;

use models::{APIError, APIFailure, Account, CardData, HTTPCode, Method, Status, TonoError};
use models_serde::decode_create_charge_error;
use serde_json::{json, Value};

fn main() {
    let big: i64 = 9_007_199_254_740_993; // 2^53 + 1, not representable as an f64
    let account = Account {
        account_id: big,
        secret: vec![1, 2, 3, 254],
        tip: Some(500),
        status: Status::Active,
        code: HTTPCode::Ok,
        method: Method::Card(CardData {
            last4: "4242".into(),
        }),
        counts: vec![(7, "a".into()), (3, "b".into())],
    };

    let wire: Value = serde_json::to_value(&account).expect("encode");
    assert!(
        wire["account_id"].is_string(),
        "i64 must encode as a JSON string, got {}",
        wire["account_id"]
    );
    assert_eq!(wire["account_id"], Value::String(big.to_string()));
    assert!(
        wire["secret"].is_string(),
        "bytes must encode as a base64 string"
    );
    assert_eq!(wire["method"]["type"], Value::String("card".into()));
    assert_eq!(wire["tip"], Value::String("500".into()));
    // An int-backed enum travels as a bare integer, not a string.
    assert_eq!(wire["code"], json!(200));
    // An @entries map travels as an array of [key, value] pairs.
    assert_eq!(wire["counts"], json!([[7, "a"], [3, "b"]]));

    // Canonical round-trip: decode then re-encode must equal the first wire JSON.
    let back: Account = serde_json::from_value(wire.clone()).expect("decode");
    let again: Value = serde_json::to_value(&back).expect("re-encode");
    assert_eq!(wire, again, "round-trip changed the JSON");

    // An open enum decodes an unknown tag leniently and preserves it: a string for
    // the string-backed enum, an integer for the int-backed one.
    let unknown_json = json!({
        "account_id": "1",
        "secret": "AAEC/g==",
        "status": "frozen",
        "code": 418,
        "method": { "type": "card", "last4": "0000" },
        "counts": []
    });
    let unknown: Account = serde_json::from_value(unknown_json).expect("decode unknown");
    assert!(
        matches!(unknown.status, Status::Unknown(ref s) if s == "frozen"),
        "an unknown enum value must pass through"
    );
    assert!(
        matches!(unknown.code, HTTPCode::Unknown(418)),
        "an unknown int-backed enum value must pass through as i64"
    );

    // Error discrimination: (status, body code) maps to the declared variant of
    // the Api category, with the @retryable predicate lowered.
    let declined = decode_create_charge_error(402, r#"{"code":"payment_declined","message":"no funds"}"#);
    assert!(declined.retryable(), "@retryable must lower into the predicate");
    match declined {
        TonoError::Api(APIFailure::PaymentDeclined(data)) => assert_eq!(data.message, "no funds"),
        other => panic!("(402, code) must map to the declared variant, got {other:?}"),
    }

    // A status alone discriminates when unambiguous; without @retryable the
    // predicate reports false.
    let limited = decode_create_charge_error(429, "{}");
    assert!(!limited.retryable(), "a non-retryable error must report false");
    assert!(
        matches!(limited, TonoError::Api(APIFailure::RateLimited(_))),
        "a bare status must discriminate when unambiguous"
    );

    // No match resolves to the concrete fallback type carrying the raw body.
    let fallback = decode_create_charge_error(402, r#"{"code":"other"}"#);
    match fallback {
        TonoError::Api(APIFailure::Undeclared(APIError { status: 402, body })) => {
            assert_eq!(body, r#"{"code":"other"}"#);
        }
        other => panic!("an unmatched code must fall back to APIError, got {other:?}"),
    }
    let undeclared = decode_create_charge_error(500, "not json");
    assert!(
        matches!(
            undeclared,
            TonoError::Api(APIFailure::Undeclared(APIError { status: 500, .. }))
        ),
        "an undeclared response must fall back to APIError"
    );

    println!("ROUNDTRIP_OK");
}
