// Code generated by tono. DO NOT EDIT.

pub mod i64_string {
    pub fn serialize<S: serde::Serializer>(v: &i64, s: S) -> Result<S::Ok, S::Error> {
        if s.is_human_readable() {
            s.serialize_str(&v.to_string())
        } else {
            serde::Serialize::serialize(v, s)
        }
    }
    pub fn deserialize<'de, D: serde::Deserializer<'de>>(d: D) -> Result<i64, D::Error> {
        if d.is_human_readable() {
            let s = <String as serde::Deserialize>::deserialize(d)?;
            s.parse().map_err(serde::de::Error::custom)
        } else {
            <i64 as serde::Deserialize>::deserialize(d)
        }
    }
    pub mod option {
        pub fn serialize<S: serde::Serializer>(v: &Option<i64>, s: S) -> Result<S::Ok, S::Error> {
            match v {
                Some(n) => super::serialize(n, s),
                None => s.serialize_none(),
            }
        }
        pub fn deserialize<'de, D: serde::Deserializer<'de>>(
            d: D,
        ) -> Result<Option<i64>, D::Error> {
            if d.is_human_readable() {
                let o = <Option<String> as serde::Deserialize>::deserialize(d)?;
                match o {
                    Some(s) => s.parse().map(Some).map_err(serde::de::Error::custom),
                    None => Ok(None),
                }
            } else {
                <Option<i64> as serde::Deserialize>::deserialize(d)
            }
        }
    }
}
