// Code generated by tono. DO NOT EDIT.

package duration

import "time"

// DurationMs parses a duration field for the runtime's millisecond value
// positions.
func DurationMs(v string) (float64, error) {
	d, err := time.ParseDuration(v)
	if err != nil {
		return 0, err
	}
	return float64(d) / float64(time.Millisecond), nil
}
