// Code generated by tono. DO NOT EDIT.

package payments

type Timestamp string

type LocalDate string

type Duration string

type Charge struct {
	ID       string            `json:"id"`
	Amount   int64             `json:"amount,string"`
	Fee      uint64            `json:"fee,string"`
	Receipt  []byte            `json:"receipt"`
	Currency string            `json:"currency"`
	Note     *string           `json:"note,omitempty"`
	Tags     []string          `json:"tags"`
	Metadata map[string]string `json:"metadata"`
	Created  Timestamp         `json:"created"`
	Status   Status            `json:"status"`
	Method   PaymentMethod     `json:"method"`
}

type Status string

const (
	StatusActive   Status = "active"
	StatusSettled  Status = "settled"
	StatusRefunded Status = "refunded"
)

type HTTPCode int

const (
	HTTPCodeOk       HTTPCode = 200
	HTTPCodeNotFound HTTPCode = 404
	HTTPCodeError    HTTPCode = 500
)

type Card struct {
	Last4 string `json:"last4"`
}

type BankAccount struct {
	Iban string `json:"iban"`
}

type PaymentMethod interface{ isPaymentMethod() }

type PaymentMethodCard struct{ Value Card }

func (PaymentMethodCard) isPaymentMethod() {}

type PaymentMethodBank struct{ Value BankAccount }

func (PaymentMethodBank) isPaymentMethod() {}
