// Code generated by tono. DO NOT EDIT.

package payments

import "encoding/json"
import "fmt"

func marshalVariant(payload any, disc, tag string) ([]byte, error) {
	b, err := json.Marshal(payload)
	if err != nil {
		return nil, err
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(b, &obj); err != nil {
		return nil, err
	}
	obj[disc], _ = json.Marshal(tag)
	return json.Marshal(obj)
}

func (c *Charge) UnmarshalJSON(b []byte) error {
	type alias Charge
	var tmp struct {
		alias
		Method json.RawMessage `json:"method"`
	}
	tmp.alias = alias(*c)
	if err := json.Unmarshal(b, &tmp); err != nil {
		return err
	}
	*c = Charge(tmp.alias)
	if len(tmp.Method) > 0 {
		m, err := unmarshalPaymentMethod(tmp.Method)
		if err != nil {
			return err
		}
		c.Method = m
	}
	return nil
}

func (m PaymentMethodCard) MarshalJSON() ([]byte, error) {
	return marshalVariant(m.Value, "kind", "card")
}

func (m PaymentMethodBank) MarshalJSON() ([]byte, error) {
	return marshalVariant(m.Value, "kind", "bank")
}

func unmarshalPaymentMethod(b []byte) (PaymentMethod, error) {
	var d map[string]json.RawMessage
	if err := json.Unmarshal(b, &d); err != nil {
		return nil, err
	}
	var tag string
	json.Unmarshal(d["kind"], &tag)
	switch tag {
	case "card":
		var p Card
		if err := json.Unmarshal(b, &p); err != nil {
			return nil, err
		}
		return PaymentMethodCard{Value: p}, nil
	case "bank":
		var p BankAccount
		if err := json.Unmarshal(b, &p); err != nil {
			return nil, err
		}
		return PaymentMethodBank{Value: p}, nil
	}
	return nil, fmt.Errorf("unknown variant %q", tag)
}

func DecodeCreateChargeError(status int, body []byte) error {
	var probe struct {
		Code string `json:"code"`
	}
	_ = json.Unmarshal(body, &probe)
	if status == 402 && probe.Code == "card_declined" {
		var data CardDeclined
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	if status == 404 {
		var data NotFound
		if json.Unmarshal(body, &data) == nil {
			return &data
		}
	}
	return &APIError{Status: status, Body: string(body)}
}
