// Code generated by tono. DO NOT EDIT.

use crate::payments::common::{PaymentMethod, Status};

use crate::payments::charges_serde::{base64_bytes, i64_string, u64_string};

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Timestamp(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct LocalDate(pub String);

#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[serde(transparent)]
pub struct Duration(pub String);

/// A small payments API that exercises the hard wire cases end to end.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Charge {
    pub id: String,
    #[serde(with = "i64_string")]
    pub amount: i64,
    #[deprecated(note = "folded into amount")]
    #[serde(with = "u64_string")]
    pub fee: u64,
    #[serde(with = "base64_bytes")]
    pub receipt: Vec<u8>,
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    pub tags: Vec<String>,
    pub metadata: std::collections::HashMap<String, String>,
    pub created: Timestamp,
    pub status: Status,
    pub method: PaymentMethod,
}

impl Charge {
    pub fn validate(&self) -> Vec<Violation> {
        let mut violations = Vec::new();
        if self.amount < 0 {
            violations.push(Violation {
                field: "amount".to_string(),
                constraint: "range".to_string(),
                message: "amount must be >= 0".to_string(),
            });
        }
        if self.currency.chars().count() < 3 {
            violations.push(Violation {
                field: "currency".to_string(),
                constraint: "length".to_string(),
                message: "currency length must be >= 3".to_string(),
            });
        }
        if self.currency.chars().count() > 3 {
            violations.push(Violation {
                field: "currency".to_string(),
                constraint: "length".to_string(),
                message: "currency length must be <= 3".to_string(),
            });
        }
        violations
    }
}

#[derive(Clone, Debug)]
pub enum HTTPCode {
    Ok,
    NotFound,
    Error,
    Unknown(i64),
}

/// A page of results with an optional continuation cursor.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Page<T> {
    pub items: Vec<T>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

/// The card issuer declined the charge.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct CardDeclined {
    pub message: String,
}

/// No charge exists for the requested id.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct NotFound {
    pub message: String,
}

#[derive(Debug)]
pub struct Violation {
    pub field: String,
    pub constraint: String,
    pub message: String,
}

#[derive(Debug)]
pub struct ValidationError {
    pub violations: Vec<Violation>,
}

#[derive(Debug)]
pub struct TransportError {
    pub cause: Box<dyn std::error::Error + Send + Sync>,
}

#[derive(Debug)]
pub struct DecodeError {
    pub path: String,
    pub expected: String,
    pub raw: String,
}

#[derive(Debug)]
pub struct ContractError {
    pub contract_name: String,
    pub cause: Box<dyn std::error::Error + Send + Sync>,
}

#[derive(Debug)]
pub struct APIError {
    pub status: u16,
    pub body: String,
}

#[derive(Debug)]
pub enum APIFailure {
    CardDeclined(CardDeclined),
    NotFound(NotFound),
    Undeclared(APIError),
}

impl APIFailure {
    pub fn retryable(&self) -> bool {
        match self {
            APIFailure::CardDeclined(_) => true,
            _ => false,
        }
    }
}

#[derive(Debug)]
pub enum TonoError {
    Validation(ValidationError),
    Transport(TransportError),
    Api(APIFailure),
    Decode(DecodeError),
    Contract(ContractError),
}

impl TonoError {
    pub fn retryable(&self) -> bool {
        match self {
            TonoError::Api(failure) => failure.retryable(),
            _ => false,
        }
    }
}

impl std::fmt::Display for TonoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TonoError::Validation(_) => write!(f, "validation failed"),
            TonoError::Transport(_) => write!(f, "transport failure"),
            TonoError::Api(_) => write!(f, "api error"),
            TonoError::Decode(_) => write!(f, "response body did not match the declared schema"),
            TonoError::Contract(e) => write!(f, "contract hook '{}' failed", e.contract_name),
        }
    }
}

impl std::error::Error for TonoError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            TonoError::Transport(e) => Some(e.cause.as_ref()),
            TonoError::Contract(e) => Some(e.cause.as_ref()),
            _ => None,
        }
    }
}

#[allow(async_fn_in_trait)]
pub trait Client {
    /// Creates a charge.
    async fn create_charge(&self, input: Charge) -> Result<Charge, TonoError>;
}
