// Code generated by tono. DO NOT EDIT.

//! Generated from the entry's declared tests: each one runs the real
//! construction path and the real method, with only the stubbed
//! transport swapped through the constructor's seam. Impl-stubbed tests
//! generate nothing for Rust: its bespoke ops expose no swappable seam.

use crate::payments::charges::types::*;

use crate::payments::charges::client::*;

// Environment pinning writes process-wide state, so every pinned test
// serializes on this lock; a poisoned lock still hands the guard over,
// so one failing test never wedges the rest of the run.
static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[test]
fn construction_construction_rejects_an_empty_api_key() {
    let _env = ENV_LOCK.lock().unwrap_or_else(|e| e.into_inner());
    std::env::remove_var("PAYMENTS_ENDPOINT");
    let result = Client::builder("".to_string()).build();
    let invalid = match result {
        Err(TonoError::Validation(e)) => e,
        Err(other) => panic!("want a validation error, got {other:?}"),
        Ok(_) => panic!("want a validation error, got ok"),
    };
    let violated: Vec<&str> = invalid
        .violations
        .iter()
        .map(|v| v.field.as_str())
        .collect();
    assert_eq!(violated, vec!["api_key"], "violated fields");
}
