// Code generated by tono. DO NOT EDIT.

use crate::payments::charges::types::Charge;
use crate::support::Duration;

use crate::payments::charges::types::*;

use crate::env::read_env;

use crate::duration::parse_duration_ms;

fn create_charge_descriptor() -> &'static tono_http_runtime::WireDescriptor {
    static DESCRIPTOR: std::sync::OnceLock<tono_http_runtime::WireDescriptor> =
        std::sync::OnceLock::new();
    DESCRIPTOR.get_or_init(|| tono_http_runtime::WireDescriptor::parse("{\"bindings\":[[\"id\",{\"kind\":\"body\"}],[\"amount\",{\"kind\":\"body\"}],[\"fee\",{\"kind\":\"body\"}],[\"receipt\",{\"kind\":\"body\"}],[\"currency\",{\"kind\":\"body\"}],[\"note\",{\"kind\":\"body\"}],[\"tags\",{\"kind\":\"body\"}],[\"metadata\",{\"kind\":\"body\"}],[\"created\",{\"kind\":\"body\"}],[\"status\",{\"kind\":\"body\"}],[\"method\",{\"kind\":\"body\"}]],\"endpoint\":[\"endpoint\"],\"errors\":[[402,\"payments.charges#card_declined\",\"card_declined\",true],[404,\"payments.charges#not_found\",null]],\"http_method\":\"POST\",\"request_headers\":[[[{\"lit\":\"X-API-Key\"}],{\"field\":[\"api_key\"]}]],\"response_bindings\":[],\"retry\":{\"max\":{\"ref\":\"max_retries\"}},\"success\":[[200,{\"args\":[],\"ref\":\"payments.charges#charge\"}]],\"timeout\":{\"ref\":\"timeout\"},\"uri\":\"/charges\"}").expect("valid wire descriptor"))
}

/// Settings are the resolved construction values of the client entry:
/// bespoke `client_init` code may overwrite any field (bespoke wins) and
/// set transport through the slots. Exactly one transport slot may be
/// set: `client` (native) or `transport` (canonical). `headers` are the
/// base request headers (bespoke auth writes here); a declared
/// `@header` wins only where nothing else set the name.
pub(crate) struct Settings {
    pub api_key: String,
    pub endpoint: String,
    pub timeout: Duration,
    pub max_retries: i32,
    pub client: Option<reqwest::Client>,
    pub transport: Option<tono_http_runtime::Transport>,
    pub headers: std::collections::HashMap<String, String>,
}

/// The payments SDK entry: the construction surface and its operations.
pub struct Client {
    #[allow(dead_code)]
    settings: Settings,
    runtime: std::sync::Arc<tono_http_runtime::Runtime>,
    hooks: Option<tono_http_runtime::Hooks>,
}

pub struct ClientBuilder {
    api_key: String,
    timeout: Option<Duration>,
    max_retries: Option<i32>,
}

impl ClientBuilder {
    pub fn with_timeout(mut self, v: Duration) -> Self {
        self.timeout = Some(v);
        self
    }
    pub fn with_max_retries(mut self, v: i32) -> Self {
        self.max_retries = Some(v);
        self
    }

    /// Resolves the declared sources top-down, runs client_init on top
    /// (bespoke wins), then the declared validation.
    pub fn build(self) -> Result<Client, TonoError> {
        let mut s = Settings {
            api_key: String::new(),
            endpoint: String::new(),
            timeout: Duration(String::new()),
            max_retries: 0,
            client: None,
            transport: None,
            headers: std::collections::HashMap::new(),
        };
        s.api_key = self.api_key;
        if let Some(v) = read_env(&"PAYMENTS_ENDPOINT") {
            s.endpoint = v;
        } else {
            s.endpoint = "https://api.payments.example.com".to_string();
        }
        if let Some(v) = self.timeout.clone() {
            s.timeout = v;
        } else {
            s.timeout = Duration("10s".to_string());
        }
        if let Some(v) = self.max_retries.clone() {
            s.max_retries = v;
        } else {
            s.max_retries = 2;
        }
        let mut violations: Vec<Violation> = Vec::new();
        if s.api_key.chars().count() < 1 {
            violations.push(Violation {
                field: "api_key".to_string(),
                constraint: "length".to_string(),
                message: "api_key length must be >= 1".to_string(),
            });
        }
        if !violations.is_empty() {
            return Err(TonoError::Validation(ValidationError { violations }));
        }
        let mut values = serde_json::Map::new();
        values.insert(
            "api_key".to_string(),
            serde_json::Value::from(s.api_key.clone()),
        );
        values.insert(
            "endpoint".to_string(),
            serde_json::Value::from(s.endpoint.clone()),
        );
        match parse_duration_ms(&s.timeout.0) {
            Ok(ms) => {
                values.insert("timeout".to_string(), serde_json::Value::from(ms));
            }
            Err(_) => {
                return Err(TonoError::Config(ConfigError {
                    message: format!("timeout: invalid duration {:?}", s.timeout.0),
                }));
            }
        }
        values.insert(
            "max_retries".to_string(),
            serde_json::Value::from(s.max_retries),
        );
        let runtime = tono_http_runtime::Runtime::new(tono_http_runtime::Options {
            base_url: String::new(),
            client: s.client.clone(),
            transport: s.transport.clone(),
            headers: s.headers.clone(),
            values,
        })
        .map_err(|e| {
            TonoError::Config(ConfigError {
                message: e.to_string(),
            })
        })?;
        Ok(Client {
            settings: s,
            runtime: std::sync::Arc::new(runtime),
            hooks: None,
        })
    }
}

impl Client {
    /// The entry point of the builder: the @arg values positionally,
    /// @with values configured through `.with_*` before `.build()`.
    pub fn builder(api_key: String) -> ClientBuilder {
        ClientBuilder {
            api_key,
            timeout: None,
            max_retries: None,
        }
    }
    pub async fn create_charge(&self, input: Charge) -> Result<Charge, TonoError> {
        if let Err(e) = input.validate() {
            return Err(TonoError::Validation(e));
        }
        let record = serde_json::to_value(&input).map_err(|e| {
            TonoError::Decode(DecodeError {
                path: "$".to_string(),
                expected: "input".to_string(),
                raw: e.to_string(),
            })
        })?;
        let outcome = self
            .runtime
            .execute(create_charge_descriptor(), &record, self.hooks.as_ref())
            .await
            .map_err(|cause| match cause.downcast::<TonoError>() {
                Ok(declared) => *declared,
                Err(other) => TonoError::Contract(ContractError {
                    contract_name: "create_charge".to_string(),
                    cause: other,
                }),
            })?;
        match outcome.kind {
            tono_http_runtime::OutcomeKind::Transport => {
                Err(TonoError::Transport(TransportError {
                    cause: outcome.cause.unwrap(),
                }))
            }
            tono_http_runtime::OutcomeKind::Error => Err(decode_create_charge_error(
                outcome.status,
                outcome.body.as_deref().unwrap_or(""),
            )),
            tono_http_runtime::OutcomeKind::Success => {
                let body = outcome.body.as_deref().unwrap_or("");
                let probe: serde_json::Value = serde_json::from_str(body).map_err(|_| {
                    TonoError::Decode(DecodeError {
                        path: "$".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    })
                })?;
                if probe.get("id").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.id".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("amount").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.amount".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("fee").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.fee".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("receipt").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.receipt".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("currency").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.currency".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("tags").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.tags".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("metadata").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.metadata".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("created").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.created".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("status").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.status".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                if probe.get("method").map(|v| v.is_null()).unwrap_or(true) {
                    return Err(TonoError::Decode(DecodeError {
                        path: "$.method".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    }));
                }
                serde_json::from_str::<Charge>(body).map_err(|_| {
                    TonoError::Decode(DecodeError {
                        path: "$".to_string(),
                        expected: "Charge".to_string(),
                        raw: body.to_string(),
                    })
                })
            }
        }
    }
}

pub fn decode_create_charge_error(status: u16, body: &str) -> TonoError {
    let value: serde_json::Value = match serde_json::from_str(body) {
        Ok(value) => value,
        Err(_) => {
            return TonoError::Api(APIFailure::Undeclared(APIError {
                status,
                body: body.to_string(),
            }))
        }
    };
    let code = value.get("code").and_then(|v| v.as_str());
    if status == 402 && code == Some("card_declined") {
        if let Ok(data) = serde_json::from_value::<CardDeclined>(value.clone()) {
            return TonoError::Api(APIFailure::CardDeclined(data));
        }
    }
    if status == 404 {
        if let Ok(data) = serde_json::from_value::<NotFound>(value.clone()) {
            return TonoError::Api(APIFailure::NotFound(data));
        }
    }
    TonoError::Api(APIFailure::Undeclared(APIError {
        status,
        body: body.to_string(),
    }))
}
