// Code generated by tono. DO NOT EDIT.

use crate::payments::common::types::{PaymentMethod, Status};
use crate::support::Timestamp;

use crate::number::{i64_string, u64_string};

use crate::bytes::base64_bytes;

/// A small payments API that exercises the hard wire cases end to end.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct Charge {
    pub id: String,
    #[serde(with = "i64_string")]
    pub amount: i64,
    #[deprecated(note = "folded into amount")]
    #[serde(with = "u64_string")]
    pub fee: u64,
    #[serde(with = "base64_bytes")]
    pub receipt: Vec<u8>,
    pub currency: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    pub tags: Vec<String>,
    pub metadata: std::collections::HashMap<String, String>,
    pub created: Timestamp,
    pub status: Status,
    pub method: PaymentMethod,
}

impl Charge {
    pub fn validate(&self) -> Result<(), ValidationError> {
        let mut violations = Vec::new();
        if self.amount < 0 {
            violations.push(Violation {
                field: "amount".to_string(),
                constraint: "range".to_string(),
                message: "amount must be >= 0".to_string(),
            });
        }
        if self.currency.chars().count() < 3 {
            violations.push(Violation {
                field: "currency".to_string(),
                constraint: "length".to_string(),
                message: "currency length must be >= 3".to_string(),
            });
        }
        if self.currency.chars().count() > 3 {
            violations.push(Violation {
                field: "currency".to_string(),
                constraint: "length".to_string(),
                message: "currency length must be <= 3".to_string(),
            });
        }
        if violations.is_empty() {
            Ok(())
        } else {
            Err(ValidationError { violations })
        }
    }
}

/// The card issuer declined the charge.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct CardDeclined {
    pub message: String,
}

/// No charge exists for the requested id.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
pub struct NotFound {
    pub message: String,
}

#[derive(Debug)]
pub struct Violation {
    pub field: String,
    pub constraint: String,
    pub message: String,
}

#[derive(Debug)]
pub struct ValidationError {
    pub violations: Vec<Violation>,
}

#[derive(Debug)]
pub struct TransportError {
    pub cause: Box<dyn std::error::Error + Send + Sync>,
}

#[derive(Debug)]
pub struct DecodeError {
    pub path: String,
    pub expected: String,
    pub raw: String,
}

#[derive(Debug)]
pub struct ContractError {
    pub contract_name: String,
    pub cause: Box<dyn std::error::Error + Send + Sync>,
}

#[derive(Debug)]
pub struct APIError {
    pub status: u16,
    pub body: String,
}

#[derive(Debug)]
pub struct ConfigError {
    pub message: String,
}

#[derive(Debug)]
pub enum APIFailure {
    CardDeclined(CardDeclined),
    NotFound(NotFound),
    Undeclared(APIError),
}

impl APIFailure {
    pub fn retryable(&self) -> bool {
        match self {
            APIFailure::CardDeclined(_) => true,
            _ => false,
        }
    }
}

#[derive(Debug)]
pub enum TonoError {
    Validation(ValidationError),
    Transport(TransportError),
    Api(APIFailure),
    Decode(DecodeError),
    Contract(ContractError),
    Config(ConfigError),
}

impl TonoError {
    pub fn retryable(&self) -> bool {
        match self {
            TonoError::Api(failure) => failure.retryable(),
            _ => false,
        }
    }
}

impl std::fmt::Display for TonoError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TonoError::Validation(_) => write!(f, "validation failed"),
            TonoError::Transport(_) => write!(f, "transport failure"),
            TonoError::Api(_) => write!(f, "api error"),
            TonoError::Decode(_) => write!(f, "response body did not match the declared schema"),
            TonoError::Contract(e) => write!(f, "contract hook '{}' failed", e.contract_name),
            TonoError::Config(e) => write!(f, "{}", e.message),
        }
    }
}

impl std::error::Error for TonoError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            TonoError::Transport(e) => Some(e.cause.as_ref()),
            TonoError::Contract(e) => Some(e.cause.as_ref()),
            _ => None,
        }
    }
}

/// The members Charge's declared shape requires present.
const CHARGE_REQUIRED_FIELDS: &[&str] = &[
    "id", "amount", "fee", "receipt", "currency", "tags", "metadata", "created", "status", "method",
];

/// Parses a Charge from its wire JSON: every required member must be present
/// (a null value counts as absent) before the typed decode runs.
pub(crate) fn decode_charge(body: &str) -> Result<Charge, TonoError> {
    let probe: serde_json::Value = serde_json::from_str(body).map_err(|_| {
        TonoError::Decode(DecodeError {
            path: "$".to_string(),
            expected: "Charge".to_string(),
            raw: body.to_string(),
        })
    })?;
    for field in CHARGE_REQUIRED_FIELDS {
        if probe.get(field).map(|v| v.is_null()).unwrap_or(true) {
            return Err(TonoError::Decode(DecodeError {
                path: format!("$.{field}"),
                expected: "Charge".to_string(),
                raw: body.to_string(),
            }));
        }
    }
    serde_json::from_str::<Charge>(body).map_err(|_| {
        TonoError::Decode(DecodeError {
            path: "$".to_string(),
            expected: "Charge".to_string(),
            raw: body.to_string(),
        })
    })
}
macro_rules! open_enum {
    ($name:ident : $wire:ty { $($variant:ident => $repr:expr),* $(,)? }) => {
        impl serde::Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                match self {
                    $($name::$variant => serde::Serialize::serialize(&$repr, s),)*
                    $name::Unknown(v) => serde::Serialize::serialize(v, s),
                }
            }
        }
        impl<'de> serde::Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let v = <$wire as serde::Deserialize>::deserialize(d)?;
                $(if v == $repr {
                    return Ok($name::$variant);
                })*
                Ok($name::Unknown(v))
            }
        }
        // The entry construction surface reads a resolved enum value back as
        // its wire spelling (a dynamic env-name lookup, a match subject, a
        // frozen descriptor value): Display gives it that conversion without
        // a serde round trip.
        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                match self {
                    $($name::$variant => write!(f, "{}", $repr),)*
                    $name::Unknown(v) => write!(f, "{}", v),
                }
            }
        }
    };
}

open_enum!(HTTPCode: i64 {
    Ok => 200i64,
    NotFound => 404i64,
    Error => 500i64,
});

#[derive(Clone, Debug, PartialEq)]
#[allow(dead_code)]
pub(crate) enum HTTPCode {
    Ok,
    NotFound,
    Error,
    Unknown(i64),
}

/// A page of results with an optional continuation cursor.
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct Page<T> {
    pub items: Vec<T>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}
