// Code generated by tono. DO NOT EDIT.

import { ClientOptions, WireDescriptor, execute } from "@tono/http-runtime-ts";
import {
  APIError,
  CardDeclined,
  CardDeclinedError,
  Charge,
  Client,
  DecodeError,
  HTTPCode,
  NotFound,
  NotFoundError,
  Timestamp,
  TonoError,
  TransportError,
} from "./charges";
import {
  decodePaymentMethod,
  decodeStatus,
  encodePaymentMethod,
  encodeStatus,
} from "./common_serde";

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  return BigInt(s);
}

export function encodeBytes(b: Uint8Array): string {
  return btoa(String.fromCharCode(...b));
}

export function decodeBytes(s: string): Uint8Array {
  return Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
}

export function encodeCharge(value: Charge): unknown {
  return {
    id: value.id,
    amount: encodeI64(value.amount),
    fee: encodeI64(value.fee),
    receipt: encodeBytes(value.receipt),
    currency: value.currency,
    note: value.note == null ? undefined : value.note,
    tags: value.tags.map((x) => x),
    metadata: Object.fromEntries(
      Object.entries(value.metadata).map(([k, v]) => [k, v]),
    ),
    created: value.created,
    status: encodeStatus(value.status),
    method: encodePaymentMethod(value.method),
  };
}

export function decodeCharge(raw: any): Charge {
  return {
    id: raw.id,
    amount: decodeI64(raw.amount),
    fee: decodeI64(raw.fee),
    receipt: decodeBytes(raw.receipt),
    currency: raw.currency,
    note: raw.note == null ? undefined : raw.note,
    tags: raw.tags.map((x: any) => x),
    metadata: Object.fromEntries(
      Object.entries(raw.metadata).map(([k, v]: [string, any]) => [k, v]),
    ),
    created: raw.created as Timestamp,
    status: decodeStatus(raw.status),
    method: decodePaymentMethod(raw.method),
  };
}

export function encodeHTTPCode(value: HTTPCode): number {
  return value;
}

export function decodeHTTPCode(raw: number): HTTPCode {
  return raw as HTTPCode;
}

export function encodeCardDeclined(value: CardDeclined): unknown {
  return {
    message: value.message,
  };
}

export function decodeCardDeclined(raw: any): CardDeclined {
  return {
    message: raw.message,
  };
}

export function encodeNotFound(value: NotFound): unknown {
  return {
    message: value.message,
  };
}

export function decodeNotFound(raw: any): NotFound {
  return {
    message: raw.message,
  };
}

export function decodeCreateChargeError(
  status: number,
  body: string,
): TonoError {
  let parsed: any;
  try {
    parsed = JSON.parse(body);
  } catch {
    return new APIError(status, body);
  }
  const code =
    typeof parsed === "object" && parsed !== null ? parsed["code"] : undefined;
  try {
    if (status === 402 && code === "card_declined") {
      return new CardDeclinedError(decodeCardDeclined(parsed), body);
    }
    if (status === 404) {
      return new NotFoundError(decodeNotFound(parsed), body);
    }
  } catch {}
  return new APIError(status, body);
}

const createChargeDescriptor: WireDescriptor = JSON.parse(
  '{"bindings":[["id",{"kind":"body"}],["amount",{"kind":"body"}],["fee",{"kind":"body"}],["receipt",{"kind":"body"}],["currency",{"kind":"body"}],["note",{"kind":"body"}],["tags",{"kind":"body"}],["metadata",{"kind":"body"}],["created",{"kind":"body"}],["status",{"kind":"body"}],["method",{"kind":"body"}]],"errors":[[402,"payments.charges#card_declined","card_declined"],[404,"payments.charges#not_found",null]],"http_method":"POST","response_bindings":[],"success":[[200,{"args":[],"ref":"payments.charges#charge"}]],"uri":"/charges"}',
);
export class HttpClient implements Client {
  constructor(private readonly options: ClientOptions) {}

  async createCharge(input: Charge): Promise<Charge> {
    const outcome = await execute(
      createChargeDescriptor,
      encodeCharge(input),
      this.options,
    );
    if (outcome.outcome === "transport") {
      throw new TransportError(outcome.cause);
    }
    if (outcome.outcome === "error") {
      throw decodeCreateChargeError(outcome.status, outcome.body);
    }
    try {
      return decodeCharge(JSON.parse(outcome.body));
    } catch {
      throw new DecodeError("$", "Charge", outcome.body);
    }
  }
}
