// Code generated by tono. DO NOT EDIT.

import {
  CanonicalTransport,
  ClientOptions,
  WireDescriptor,
  execute,
} from "@tono/http-runtime-ts";
import {
  APIError,
  CardDeclined,
  CardDeclinedError,
  Charge,
  DecodeError,
  Duration,
  HTTPCode,
  NotFound,
  NotFoundError,
  Timestamp,
  TonoError,
  TransportError,
  ValidationError,
  Violation,
} from "./charges";
import {
  decodePaymentMethod,
  decodeStatus,
  encodePaymentMethod,
  encodeStatus,
} from "./common_serde";

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  return BigInt(s);
}

export function encodeBytes(b: Uint8Array): string {
  return btoa(String.fromCharCode(...b));
}

export function decodeBytes(s: string): Uint8Array {
  return Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
}

export function encodeCharge(value: Charge): unknown {
  return {
    id: value.id,
    amount: encodeI64(value.amount),
    fee: encodeI64(value.fee),
    receipt: encodeBytes(value.receipt),
    currency: value.currency,
    note: value.note == null ? undefined : value.note,
    tags: value.tags.map((x) => x),
    metadata: Object.fromEntries(
      Object.entries(value.metadata).map(([k, v]) => [k, v]),
    ),
    created: value.created,
    status: encodeStatus(value.status),
    method: encodePaymentMethod(value.method),
  };
}

export function decodeCharge(raw: any): Charge {
  return {
    id: raw.id,
    amount: decodeI64(raw.amount),
    fee: decodeI64(raw.fee),
    receipt: decodeBytes(raw.receipt),
    currency: raw.currency,
    note: raw.note == null ? undefined : raw.note,
    tags: raw.tags.map((x: any) => x),
    metadata: Object.fromEntries(
      Object.entries(raw.metadata).map(([k, v]: [string, any]) => [k, v]),
    ),
    created: raw.created as Timestamp,
    status: decodeStatus(raw.status),
    method: decodePaymentMethod(raw.method),
  };
}

export function encodeHTTPCode(value: HTTPCode): number {
  return value;
}

export function decodeHTTPCode(raw: number): HTTPCode {
  return raw as HTTPCode;
}

export function encodeCardDeclined(value: CardDeclined): unknown {
  return {
    message: value.message,
  };
}

export function decodeCardDeclined(raw: any): CardDeclined {
  return {
    message: raw.message,
  };
}

export function encodeNotFound(value: NotFound): unknown {
  return {
    message: value.message,
  };
}

export function decodeNotFound(raw: any): NotFound {
  return {
    message: raw.message,
  };
}

// Settings are the resolved construction values of the client entry,
// handed to the client_init hook before validation: bespoke code may
// overwrite any field (bespoke wins) and set transport through the slots.
// Exactly one transport slot may be set: fetch (native) or transport
// (canonical). headers are the base request headers (bespoke auth writes
// here); a declared @header wins only where nothing else set the name.
export interface Settings {
  apiKey: string;
  endpoint: string;
  timeout: Duration;
  maxRetries: number;
  fetch?: typeof fetch;
  transport?: CanonicalTransport;
  headers: Record<string, string>;
}

// ClientConfig carries the optional (@with) construction values of Client.
export interface ClientConfig {
  timeout?: Duration;
  maxRetries?: number;
}

const createChargeDescriptor: WireDescriptor = JSON.parse(
  '{"bindings":[["id",{"kind":"body"}],["amount",{"kind":"body"}],["fee",{"kind":"body"}],["receipt",{"kind":"body"}],["currency",{"kind":"body"}],["note",{"kind":"body"}],["tags",{"kind":"body"}],["metadata",{"kind":"body"}],["created",{"kind":"body"}],["status",{"kind":"body"}],["method",{"kind":"body"}]],"endpoint":["endpoint"],"errors":[[402,"payments.charges#card_declined","card_declined",true],[404,"payments.charges#not_found",null]],"http_method":"POST","request_headers":[[[{"lit":"X-API-Key"}],{"field":["api_key"]}]],"response_bindings":[],"retry":{"max":{"ref":"max_retries"}},"success":[[200,{"args":[],"ref":"payments.charges#charge"}]],"timeout":{"ref":"timeout"},"uri":"/charges"}',
);

// The payments SDK entry: the construction surface and its operations.
// Client is the generated SDK client the client entry declares. The
// constructor takes the @arg values positionally and the @with values as a
// config object; construction resolves the declared sources, runs the
// client_init bridge, validates, and freezes the runtime options.
export class Client {
  readonly settings: Settings;
  private readonly options: ClientOptions;
  constructor(apiKey: string, config: ClientConfig = {}) {
    const s: Settings = {
      apiKey: "",
      endpoint: "",
      timeout: "" as unknown as Duration,
      maxRetries: 0,
      headers: {},
    };
    s.apiKey = apiKey;
    let endpointSet = false;
    if (!endpointSet) {
      const v = readEnv("PAYMENTS_ENDPOINT");
      if (v !== undefined) {
        s.endpoint = v;
        endpointSet = true;
      }
    }
    if (!endpointSet) {
      s.endpoint = "https://api.payments.example.com";
    }
    let timeoutSet = false;
    if (config.timeout !== undefined) {
      s.timeout = config.timeout;
      timeoutSet = true;
    }
    if (!timeoutSet) {
      s.timeout = "10s" as Duration;
    }
    let maxRetriesSet = false;
    if (config.maxRetries !== undefined) {
      s.maxRetries = config.maxRetries;
      maxRetriesSet = true;
    }
    if (!maxRetriesSet) {
      s.maxRetries = 2;
    }
    const violations: Violation[] = [];
    if ([...s.apiKey].length < 1) {
      violations.push({
        field: "api_key",
        constraint: "length",
        message: "api_key length must be >= 1",
      });
    }
    if (violations.length > 0) {
      throw new ValidationError(violations);
    }
    const values: Record<string, unknown> = {};
    values["api_key"] = s.apiKey;
    values["endpoint"] = s.endpoint;
    try {
      values["timeout"] = durationToMs(String(s.timeout));
    } catch {
      throw new Error(
        `timeout: invalid duration ${JSON.stringify(String(s.timeout))}`,
      );
    }
    values["max_retries"] = s.maxRetries;
    this.settings = s;
    this.options = {
      baseUrl: "",
      fetch: s.fetch,
      transport: s.transport,
      headers: s.headers,
      values,
    };
  }

  async createCharge(input: Charge): Promise<Charge> {
    const outcome = await execute(
      createChargeDescriptor,
      encodeCharge(input),
      this.options,
    );
    if (outcome.outcome === "transport") {
      throw new TransportError(outcome.cause);
    }
    if (outcome.outcome === "error") {
      throw decodeCreateChargeError(outcome.status, outcome.body);
    }
    try {
      return decodeCharge(JSON.parse(outcome.body));
    } catch {
      throw new DecodeError("$", "Charge", outcome.body);
    }
  }
}

export function decodeCreateChargeError(
  status: number,
  body: string,
): TonoError {
  let parsed: any;
  try {
    parsed = JSON.parse(body);
  } catch {
    return new APIError(status, body);
  }
  const code =
    typeof parsed === "object" && parsed !== null ? parsed["code"] : undefined;
  try {
    if (status === 402 && code === "card_declined") {
      return new CardDeclinedError(decodeCardDeclined(parsed), body);
    }
    if (status === 404) {
      return new NotFoundError(decodeNotFound(parsed), body);
    }
  } catch {}
  return new APIError(status, body);
}

// readEnv treats an unset and an empty variable the same: empty means
// not set, per the declared-source contract.
function readEnv(name: string): string | undefined {
  const env = (
    globalThis as { process?: { env?: Record<string, string | undefined> } }
  ).process?.env;
  const v = env?.[name];
  return v === undefined || v === "" ? undefined : v;
}

// durationToMs parses the duration spelling shared across targets
// (Go's ParseDuration grammar: optional sign, bare zero, unit runs)
// into the runtime's millisecond values.
function durationToMs(v: string): number {
  let rest = v;
  let sign = 1;
  if (rest.startsWith("-")) {
    sign = -1;
    rest = rest.slice(1);
  } else if (rest.startsWith("+")) {
    rest = rest.slice(1);
  }
  if (rest === "0") {
    return 0;
  }
  const re = /(\d+(?:\.\d+)?)(ns|us|\u00b5s|ms|s|m|h)/gy;
  const unit: Record<string, number> = {
    ns: 1e-6,
    us: 1e-3,
    "\u00b5s": 1e-3,
    ms: 1,
    s: 1000,
    m: 60000,
    h: 3600000,
  };
  let total = 0;
  let consumed = 0;
  for (let m = re.exec(rest); m !== null; m = re.exec(rest)) {
    total += Number(m[1]) * unit[m[2]];
    consumed = re.lastIndex;
  }
  if (consumed !== rest.length || rest.length === 0) {
    throw new Error(`invalid duration ${JSON.stringify(v)}`);
  }
  return sign * total;
}
