// Code generated by tono. DO NOT EDIT.

import { BankAccount, Card, PaymentMethod, Status } from "./common";

export function encodeI64(v: bigint): string {
  return v.toString();
}

export function decodeI64(s: string): bigint {
  const n = BigInt(s);
  if (n < -9223372036854775808n || n > 9223372036854775807n) {
    throw new RangeError(`i64 out of range: ${s}`);
  }
  return n;
}

export function decodeU64(s: string): bigint {
  const n = BigInt(s);
  if (n < 0n || n > 18446744073709551615n) {
    throw new RangeError(`u64 out of range: ${s}`);
  }
  return n;
}

export function encodeBytes(b: Uint8Array): string {
  return btoa(String.fromCharCode(...b));
}

export function decodeBytes(s: string): Uint8Array {
  return Uint8Array.from(atob(s), (c) => c.charCodeAt(0));
}

export function encodeStatus(value: Status): string {
  return value;
}

export function decodeStatus(raw: string): Status {
  return raw as Status;
}

export function encodeCard(value: Card): unknown {
  return {
    last4: value.last4,
  };
}

export function decodeCard(raw: any): Card {
  return {
    last4: raw.last4,
  };
}

export function encodeBankAccount(value: BankAccount): unknown {
  return {
    iban: value.iban,
  };
}

export function decodeBankAccount(raw: any): BankAccount {
  return {
    iban: raw.iban,
  };
}

export function encodePaymentMethod(value: PaymentMethod): unknown {
  switch (value.kind) {
    case "card":
      return { kind: "card", ...(encodeCard(value as any) as object) };
    case "bank":
      return { kind: "bank", ...(encodeBankAccount(value as any) as object) };
  }
  throw new Error("unknown variant");
}

export function decodePaymentMethod(raw: any): PaymentMethod {
  switch (raw.kind) {
    case "card":
      return { kind: "card", ...(decodeCard(raw) as object) } as PaymentMethod;
    case "bank":
      return {
        kind: "bank",
        ...(decodeBankAccount(raw) as object),
      } as PaymentMethod;
  }
  throw new Error("unknown variant");
}
