// Code generated by tono. DO NOT EDIT.

export type Timestamp = string & { readonly __brand: "Timestamp" };

export type LocalDate = string & { readonly __brand: "LocalDate" };

export type Duration = string & { readonly __brand: "Duration" };

export type Status = "active" | "settled" | "refunded" | (string & {});

export interface Card {
  last4: string;
}

export interface BankAccount {
  iban: string;
}

export type PaymentMethod =
  | ({ kind: "card" } & Card)
  | ({ kind: "bank" } & BankAccount);
